package com.gd.datachx.entity;

import java.math.BigDecimal;
import java.util.Date;

public class TBdBranchInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_branch_info.branch_no
     *
     * @mbggenerated
     */
    private String branchNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_branch_info.branch_name
     *
     * @mbggenerated
     */
    private String branchName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_branch_info.property
     *
     * @mbggenerated
     */
    private String property;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_branch_info.branch_man
     *
     * @mbggenerated
     */
    private String branchMan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_branch_info.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_branch_info.zip
     *
     * @mbggenerated
     */
    private String zip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_branch_info.branch_email
     *
     * @mbggenerated
     */
    private String branchEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_branch_info.branch_tel
     *
     * @mbggenerated
     */
    private String branchTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_branch_info.branch_fax
     *
     * @mbggenerated
     */
    private String branchFax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_branch_info.display_flag
     *
     * @mbggenerated
     */
    private String displayFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_branch_info.area
     *
     * @mbggenerated
     */
    private BigDecimal area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_branch_info.trade_type
     *
     * @mbggenerated
     */
    private String tradeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_branch_info.com_grant
     *
     * @mbggenerated
     */
    private String comGrant;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_branch_info.account
     *
     * @mbggenerated
     */
    private String account;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_branch_info.com_init
     *
     * @mbggenerated
     */
    private String comInit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_branch_info.init_date
     *
     * @mbggenerated
     */
    private Date initDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_branch_info.indep_bal
     *
     * @mbggenerated
     */
    private String indepBal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_branch_info.dc_no
     *
     * @mbggenerated
     */
    private String dcNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_branch_info.com_date_up
     *
     * @mbggenerated
     */
    private Date comDateUp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_branch_info.com_date_down
     *
     * @mbggenerated
     */
    private Date comDateDown;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_branch_info.com_oper_up
     *
     * @mbggenerated
     */
    private String comOperUp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_branch_info.com_oper_down
     *
     * @mbggenerated
     */
    private String comOperDown;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_branch_info.pi_limited
     *
     * @mbggenerated
     */
    private BigDecimal piLimited;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_branch_info.dec_rate
     *
     * @mbggenerated
     */
    private BigDecimal decRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_branch_info.price_ratio
     *
     * @mbggenerated
     */
    private BigDecimal priceRatio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_branch_info.price_option
     *
     * @mbggenerated
     */
    private String priceOption;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_branch_info.vip_flag
     *
     * @mbggenerated
     */
    private String vipFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_branch_info.vip_quota
     *
     * @mbggenerated
     */
    private BigDecimal vipQuota;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_branch_info.vip_type
     *
     * @mbggenerated
     */
    private String vipType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_branch_info.acc_flag
     *
     * @mbggenerated
     */
    private String accFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_branch_info.query_local_flag
     *
     * @mbggenerated
     */
    private String queryLocalFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_branch_info.operator_flag
     *
     * @mbggenerated
     */
    private String operatorFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_branch_info.branch_clsno
     *
     * @mbggenerated
     */
    private String branchClsno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_branch_info.zbtg_flag
     *
     * @mbggenerated
     */
    private String zbtgFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_branch_info.version_flag
     *
     * @mbggenerated
     */
    private String versionFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_branch_info.num_oper
     *
     * @mbggenerated
     */
    private String numOper;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_branch_info.query_self
     *
     * @mbggenerated
     */
    private String querySelf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_branch_info.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_branch_info.re_branch
     *
     * @mbggenerated
     */
    private String reBranch;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_branch_info.branch_no
     *
     * @return the value of t_bd_branch_info.branch_no
     *
     * @mbggenerated
     */
    public String getBranchNo() {
        return branchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_branch_info.branch_no
     *
     * @param branchNo the value for t_bd_branch_info.branch_no
     *
     * @mbggenerated
     */
    public void setBranchNo(String branchNo) {
        this.branchNo = branchNo == null ? null : branchNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_branch_info.branch_name
     *
     * @return the value of t_bd_branch_info.branch_name
     *
     * @mbggenerated
     */
    public String getBranchName() {
        return branchName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_branch_info.branch_name
     *
     * @param branchName the value for t_bd_branch_info.branch_name
     *
     * @mbggenerated
     */
    public void setBranchName(String branchName) {
        this.branchName = branchName == null ? null : branchName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_branch_info.property
     *
     * @return the value of t_bd_branch_info.property
     *
     * @mbggenerated
     */
    public String getProperty() {
        return property;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_branch_info.property
     *
     * @param property the value for t_bd_branch_info.property
     *
     * @mbggenerated
     */
    public void setProperty(String property) {
        this.property = property == null ? null : property.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_branch_info.branch_man
     *
     * @return the value of t_bd_branch_info.branch_man
     *
     * @mbggenerated
     */
    public String getBranchMan() {
        return branchMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_branch_info.branch_man
     *
     * @param branchMan the value for t_bd_branch_info.branch_man
     *
     * @mbggenerated
     */
    public void setBranchMan(String branchMan) {
        this.branchMan = branchMan == null ? null : branchMan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_branch_info.address
     *
     * @return the value of t_bd_branch_info.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_branch_info.address
     *
     * @param address the value for t_bd_branch_info.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_branch_info.zip
     *
     * @return the value of t_bd_branch_info.zip
     *
     * @mbggenerated
     */
    public String getZip() {
        return zip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_branch_info.zip
     *
     * @param zip the value for t_bd_branch_info.zip
     *
     * @mbggenerated
     */
    public void setZip(String zip) {
        this.zip = zip == null ? null : zip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_branch_info.branch_email
     *
     * @return the value of t_bd_branch_info.branch_email
     *
     * @mbggenerated
     */
    public String getBranchEmail() {
        return branchEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_branch_info.branch_email
     *
     * @param branchEmail the value for t_bd_branch_info.branch_email
     *
     * @mbggenerated
     */
    public void setBranchEmail(String branchEmail) {
        this.branchEmail = branchEmail == null ? null : branchEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_branch_info.branch_tel
     *
     * @return the value of t_bd_branch_info.branch_tel
     *
     * @mbggenerated
     */
    public String getBranchTel() {
        return branchTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_branch_info.branch_tel
     *
     * @param branchTel the value for t_bd_branch_info.branch_tel
     *
     * @mbggenerated
     */
    public void setBranchTel(String branchTel) {
        this.branchTel = branchTel == null ? null : branchTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_branch_info.branch_fax
     *
     * @return the value of t_bd_branch_info.branch_fax
     *
     * @mbggenerated
     */
    public String getBranchFax() {
        return branchFax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_branch_info.branch_fax
     *
     * @param branchFax the value for t_bd_branch_info.branch_fax
     *
     * @mbggenerated
     */
    public void setBranchFax(String branchFax) {
        this.branchFax = branchFax == null ? null : branchFax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_branch_info.display_flag
     *
     * @return the value of t_bd_branch_info.display_flag
     *
     * @mbggenerated
     */
    public String getDisplayFlag() {
        return displayFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_branch_info.display_flag
     *
     * @param displayFlag the value for t_bd_branch_info.display_flag
     *
     * @mbggenerated
     */
    public void setDisplayFlag(String displayFlag) {
        this.displayFlag = displayFlag == null ? null : displayFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_branch_info.area
     *
     * @return the value of t_bd_branch_info.area
     *
     * @mbggenerated
     */
    public BigDecimal getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_branch_info.area
     *
     * @param area the value for t_bd_branch_info.area
     *
     * @mbggenerated
     */
    public void setArea(BigDecimal area) {
        this.area = area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_branch_info.trade_type
     *
     * @return the value of t_bd_branch_info.trade_type
     *
     * @mbggenerated
     */
    public String getTradeType() {
        return tradeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_branch_info.trade_type
     *
     * @param tradeType the value for t_bd_branch_info.trade_type
     *
     * @mbggenerated
     */
    public void setTradeType(String tradeType) {
        this.tradeType = tradeType == null ? null : tradeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_branch_info.com_grant
     *
     * @return the value of t_bd_branch_info.com_grant
     *
     * @mbggenerated
     */
    public String getComGrant() {
        return comGrant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_branch_info.com_grant
     *
     * @param comGrant the value for t_bd_branch_info.com_grant
     *
     * @mbggenerated
     */
    public void setComGrant(String comGrant) {
        this.comGrant = comGrant == null ? null : comGrant.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_branch_info.account
     *
     * @return the value of t_bd_branch_info.account
     *
     * @mbggenerated
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_branch_info.account
     *
     * @param account the value for t_bd_branch_info.account
     *
     * @mbggenerated
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_branch_info.com_init
     *
     * @return the value of t_bd_branch_info.com_init
     *
     * @mbggenerated
     */
    public String getComInit() {
        return comInit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_branch_info.com_init
     *
     * @param comInit the value for t_bd_branch_info.com_init
     *
     * @mbggenerated
     */
    public void setComInit(String comInit) {
        this.comInit = comInit == null ? null : comInit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_branch_info.init_date
     *
     * @return the value of t_bd_branch_info.init_date
     *
     * @mbggenerated
     */
    public Date getInitDate() {
        return initDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_branch_info.init_date
     *
     * @param initDate the value for t_bd_branch_info.init_date
     *
     * @mbggenerated
     */
    public void setInitDate(Date initDate) {
        this.initDate = initDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_branch_info.indep_bal
     *
     * @return the value of t_bd_branch_info.indep_bal
     *
     * @mbggenerated
     */
    public String getIndepBal() {
        return indepBal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_branch_info.indep_bal
     *
     * @param indepBal the value for t_bd_branch_info.indep_bal
     *
     * @mbggenerated
     */
    public void setIndepBal(String indepBal) {
        this.indepBal = indepBal == null ? null : indepBal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_branch_info.dc_no
     *
     * @return the value of t_bd_branch_info.dc_no
     *
     * @mbggenerated
     */
    public String getDcNo() {
        return dcNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_branch_info.dc_no
     *
     * @param dcNo the value for t_bd_branch_info.dc_no
     *
     * @mbggenerated
     */
    public void setDcNo(String dcNo) {
        this.dcNo = dcNo == null ? null : dcNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_branch_info.com_date_up
     *
     * @return the value of t_bd_branch_info.com_date_up
     *
     * @mbggenerated
     */
    public Date getComDateUp() {
        return comDateUp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_branch_info.com_date_up
     *
     * @param comDateUp the value for t_bd_branch_info.com_date_up
     *
     * @mbggenerated
     */
    public void setComDateUp(Date comDateUp) {
        this.comDateUp = comDateUp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_branch_info.com_date_down
     *
     * @return the value of t_bd_branch_info.com_date_down
     *
     * @mbggenerated
     */
    public Date getComDateDown() {
        return comDateDown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_branch_info.com_date_down
     *
     * @param comDateDown the value for t_bd_branch_info.com_date_down
     *
     * @mbggenerated
     */
    public void setComDateDown(Date comDateDown) {
        this.comDateDown = comDateDown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_branch_info.com_oper_up
     *
     * @return the value of t_bd_branch_info.com_oper_up
     *
     * @mbggenerated
     */
    public String getComOperUp() {
        return comOperUp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_branch_info.com_oper_up
     *
     * @param comOperUp the value for t_bd_branch_info.com_oper_up
     *
     * @mbggenerated
     */
    public void setComOperUp(String comOperUp) {
        this.comOperUp = comOperUp == null ? null : comOperUp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_branch_info.com_oper_down
     *
     * @return the value of t_bd_branch_info.com_oper_down
     *
     * @mbggenerated
     */
    public String getComOperDown() {
        return comOperDown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_branch_info.com_oper_down
     *
     * @param comOperDown the value for t_bd_branch_info.com_oper_down
     *
     * @mbggenerated
     */
    public void setComOperDown(String comOperDown) {
        this.comOperDown = comOperDown == null ? null : comOperDown.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_branch_info.pi_limited
     *
     * @return the value of t_bd_branch_info.pi_limited
     *
     * @mbggenerated
     */
    public BigDecimal getPiLimited() {
        return piLimited;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_branch_info.pi_limited
     *
     * @param piLimited the value for t_bd_branch_info.pi_limited
     *
     * @mbggenerated
     */
    public void setPiLimited(BigDecimal piLimited) {
        this.piLimited = piLimited;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_branch_info.dec_rate
     *
     * @return the value of t_bd_branch_info.dec_rate
     *
     * @mbggenerated
     */
    public BigDecimal getDecRate() {
        return decRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_branch_info.dec_rate
     *
     * @param decRate the value for t_bd_branch_info.dec_rate
     *
     * @mbggenerated
     */
    public void setDecRate(BigDecimal decRate) {
        this.decRate = decRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_branch_info.price_ratio
     *
     * @return the value of t_bd_branch_info.price_ratio
     *
     * @mbggenerated
     */
    public BigDecimal getPriceRatio() {
        return priceRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_branch_info.price_ratio
     *
     * @param priceRatio the value for t_bd_branch_info.price_ratio
     *
     * @mbggenerated
     */
    public void setPriceRatio(BigDecimal priceRatio) {
        this.priceRatio = priceRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_branch_info.price_option
     *
     * @return the value of t_bd_branch_info.price_option
     *
     * @mbggenerated
     */
    public String getPriceOption() {
        return priceOption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_branch_info.price_option
     *
     * @param priceOption the value for t_bd_branch_info.price_option
     *
     * @mbggenerated
     */
    public void setPriceOption(String priceOption) {
        this.priceOption = priceOption == null ? null : priceOption.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_branch_info.vip_flag
     *
     * @return the value of t_bd_branch_info.vip_flag
     *
     * @mbggenerated
     */
    public String getVipFlag() {
        return vipFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_branch_info.vip_flag
     *
     * @param vipFlag the value for t_bd_branch_info.vip_flag
     *
     * @mbggenerated
     */
    public void setVipFlag(String vipFlag) {
        this.vipFlag = vipFlag == null ? null : vipFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_branch_info.vip_quota
     *
     * @return the value of t_bd_branch_info.vip_quota
     *
     * @mbggenerated
     */
    public BigDecimal getVipQuota() {
        return vipQuota;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_branch_info.vip_quota
     *
     * @param vipQuota the value for t_bd_branch_info.vip_quota
     *
     * @mbggenerated
     */
    public void setVipQuota(BigDecimal vipQuota) {
        this.vipQuota = vipQuota;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_branch_info.vip_type
     *
     * @return the value of t_bd_branch_info.vip_type
     *
     * @mbggenerated
     */
    public String getVipType() {
        return vipType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_branch_info.vip_type
     *
     * @param vipType the value for t_bd_branch_info.vip_type
     *
     * @mbggenerated
     */
    public void setVipType(String vipType) {
        this.vipType = vipType == null ? null : vipType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_branch_info.acc_flag
     *
     * @return the value of t_bd_branch_info.acc_flag
     *
     * @mbggenerated
     */
    public String getAccFlag() {
        return accFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_branch_info.acc_flag
     *
     * @param accFlag the value for t_bd_branch_info.acc_flag
     *
     * @mbggenerated
     */
    public void setAccFlag(String accFlag) {
        this.accFlag = accFlag == null ? null : accFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_branch_info.query_local_flag
     *
     * @return the value of t_bd_branch_info.query_local_flag
     *
     * @mbggenerated
     */
    public String getQueryLocalFlag() {
        return queryLocalFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_branch_info.query_local_flag
     *
     * @param queryLocalFlag the value for t_bd_branch_info.query_local_flag
     *
     * @mbggenerated
     */
    public void setQueryLocalFlag(String queryLocalFlag) {
        this.queryLocalFlag = queryLocalFlag == null ? null : queryLocalFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_branch_info.operator_flag
     *
     * @return the value of t_bd_branch_info.operator_flag
     *
     * @mbggenerated
     */
    public String getOperatorFlag() {
        return operatorFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_branch_info.operator_flag
     *
     * @param operatorFlag the value for t_bd_branch_info.operator_flag
     *
     * @mbggenerated
     */
    public void setOperatorFlag(String operatorFlag) {
        this.operatorFlag = operatorFlag == null ? null : operatorFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_branch_info.branch_clsno
     *
     * @return the value of t_bd_branch_info.branch_clsno
     *
     * @mbggenerated
     */
    public String getBranchClsno() {
        return branchClsno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_branch_info.branch_clsno
     *
     * @param branchClsno the value for t_bd_branch_info.branch_clsno
     *
     * @mbggenerated
     */
    public void setBranchClsno(String branchClsno) {
        this.branchClsno = branchClsno == null ? null : branchClsno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_branch_info.zbtg_flag
     *
     * @return the value of t_bd_branch_info.zbtg_flag
     *
     * @mbggenerated
     */
    public String getZbtgFlag() {
        return zbtgFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_branch_info.zbtg_flag
     *
     * @param zbtgFlag the value for t_bd_branch_info.zbtg_flag
     *
     * @mbggenerated
     */
    public void setZbtgFlag(String zbtgFlag) {
        this.zbtgFlag = zbtgFlag == null ? null : zbtgFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_branch_info.version_flag
     *
     * @return the value of t_bd_branch_info.version_flag
     *
     * @mbggenerated
     */
    public String getVersionFlag() {
        return versionFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_branch_info.version_flag
     *
     * @param versionFlag the value for t_bd_branch_info.version_flag
     *
     * @mbggenerated
     */
    public void setVersionFlag(String versionFlag) {
        this.versionFlag = versionFlag == null ? null : versionFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_branch_info.num_oper
     *
     * @return the value of t_bd_branch_info.num_oper
     *
     * @mbggenerated
     */
    public String getNumOper() {
        return numOper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_branch_info.num_oper
     *
     * @param numOper the value for t_bd_branch_info.num_oper
     *
     * @mbggenerated
     */
    public void setNumOper(String numOper) {
        this.numOper = numOper == null ? null : numOper.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_branch_info.query_self
     *
     * @return the value of t_bd_branch_info.query_self
     *
     * @mbggenerated
     */
    public String getQuerySelf() {
        return querySelf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_branch_info.query_self
     *
     * @param querySelf the value for t_bd_branch_info.query_self
     *
     * @mbggenerated
     */
    public void setQuerySelf(String querySelf) {
        this.querySelf = querySelf == null ? null : querySelf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_branch_info.status
     *
     * @return the value of t_bd_branch_info.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_branch_info.status
     *
     * @param status the value for t_bd_branch_info.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_branch_info.re_branch
     *
     * @return the value of t_bd_branch_info.re_branch
     *
     * @mbggenerated
     */
    public String getReBranch() {
        return reBranch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_branch_info.re_branch
     *
     * @param reBranch the value for t_bd_branch_info.re_branch
     *
     * @mbggenerated
     */
    public void setReBranch(String reBranch) {
        this.reBranch = reBranch == null ? null : reBranch.trim();
    }
}