package com.gd.datachx.entity;

import java.math.BigDecimal;

public class TBdItemCls {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_item_cls.item_clsno
     *
     * @mbggenerated
     */
    private String itemClsno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_item_cls.item_clsname
     *
     * @mbggenerated
     */
    private String itemClsname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_item_cls.item_flag
     *
     * @mbggenerated
     */
    private String itemFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_item_cls.cls_parent
     *
     * @mbggenerated
     */
    private String clsParent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_item_cls.display_flag
     *
     * @mbggenerated
     */
    private String displayFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_item_cls.return_rate
     *
     * @mbggenerated
     */
    private BigDecimal returnRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_item_cls.comp_rate
     *
     * @mbggenerated
     */
    private BigDecimal compRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_item_cls.trans_flag
     *
     * @mbggenerated
     */
    private String transFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_item_cls.item_clsno
     *
     * @return the value of t_bd_item_cls.item_clsno
     *
     * @mbggenerated
     */
    public String getItemClsno() {
        return itemClsno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_item_cls.item_clsno
     *
     * @param itemClsno the value for t_bd_item_cls.item_clsno
     *
     * @mbggenerated
     */
    public void setItemClsno(String itemClsno) {
        this.itemClsno = itemClsno == null ? null : itemClsno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_item_cls.item_clsname
     *
     * @return the value of t_bd_item_cls.item_clsname
     *
     * @mbggenerated
     */
    public String getItemClsname() {
        return itemClsname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_item_cls.item_clsname
     *
     * @param itemClsname the value for t_bd_item_cls.item_clsname
     *
     * @mbggenerated
     */
    public void setItemClsname(String itemClsname) {
        this.itemClsname = itemClsname == null ? null : itemClsname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_item_cls.item_flag
     *
     * @return the value of t_bd_item_cls.item_flag
     *
     * @mbggenerated
     */
    public String getItemFlag() {
        return itemFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_item_cls.item_flag
     *
     * @param itemFlag the value for t_bd_item_cls.item_flag
     *
     * @mbggenerated
     */
    public void setItemFlag(String itemFlag) {
        this.itemFlag = itemFlag == null ? null : itemFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_item_cls.cls_parent
     *
     * @return the value of t_bd_item_cls.cls_parent
     *
     * @mbggenerated
     */
    public String getClsParent() {
        return clsParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_item_cls.cls_parent
     *
     * @param clsParent the value for t_bd_item_cls.cls_parent
     *
     * @mbggenerated
     */
    public void setClsParent(String clsParent) {
        this.clsParent = clsParent == null ? null : clsParent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_item_cls.display_flag
     *
     * @return the value of t_bd_item_cls.display_flag
     *
     * @mbggenerated
     */
    public String getDisplayFlag() {
        return displayFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_item_cls.display_flag
     *
     * @param displayFlag the value for t_bd_item_cls.display_flag
     *
     * @mbggenerated
     */
    public void setDisplayFlag(String displayFlag) {
        this.displayFlag = displayFlag == null ? null : displayFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_item_cls.return_rate
     *
     * @return the value of t_bd_item_cls.return_rate
     *
     * @mbggenerated
     */
    public BigDecimal getReturnRate() {
        return returnRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_item_cls.return_rate
     *
     * @param returnRate the value for t_bd_item_cls.return_rate
     *
     * @mbggenerated
     */
    public void setReturnRate(BigDecimal returnRate) {
        this.returnRate = returnRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_item_cls.comp_rate
     *
     * @return the value of t_bd_item_cls.comp_rate
     *
     * @mbggenerated
     */
    public BigDecimal getCompRate() {
        return compRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_item_cls.comp_rate
     *
     * @param compRate the value for t_bd_item_cls.comp_rate
     *
     * @mbggenerated
     */
    public void setCompRate(BigDecimal compRate) {
        this.compRate = compRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_item_cls.trans_flag
     *
     * @return the value of t_bd_item_cls.trans_flag
     *
     * @mbggenerated
     */
    public String getTransFlag() {
        return transFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_item_cls.trans_flag
     *
     * @param transFlag the value for t_bd_item_cls.trans_flag
     *
     * @mbggenerated
     */
    public void setTransFlag(String transFlag) {
        this.transFlag = transFlag == null ? null : transFlag.trim();
    }
}