package com.gd.datachx.entity;

import java.math.BigDecimal;

public class TBdItemBrand {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_item_brand.item_brandno
     *
     * @mbggenerated
     */
    private String itemBrandno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_item_brand.item_brandname
     *
     * @mbggenerated
     */
    private String itemBrandname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_item_brand.item_flag
     *
     * @mbggenerated
     */
    private String itemFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_item_brand.brand_parent
     *
     * @mbggenerated
     */
    private String brandParent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_item_brand.display_flag
     *
     * @mbggenerated
     */
    private String displayFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_item_brand.return_rate
     *
     * @mbggenerated
     */
    private BigDecimal returnRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_item_brand.comp_rate
     *
     * @mbggenerated
     */
    private BigDecimal compRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_item_brand.trans_flag
     *
     * @mbggenerated
     */
    private String transFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_item_brand.item_brandno
     *
     * @return the value of t_bd_item_brand.item_brandno
     *
     * @mbggenerated
     */
    public String getItemBrandno() {
        return itemBrandno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_item_brand.item_brandno
     *
     * @param itemBrandno the value for t_bd_item_brand.item_brandno
     *
     * @mbggenerated
     */
    public void setItemBrandno(String itemBrandno) {
        this.itemBrandno = itemBrandno == null ? null : itemBrandno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_item_brand.item_brandname
     *
     * @return the value of t_bd_item_brand.item_brandname
     *
     * @mbggenerated
     */
    public String getItemBrandname() {
        return itemBrandname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_item_brand.item_brandname
     *
     * @param itemBrandname the value for t_bd_item_brand.item_brandname
     *
     * @mbggenerated
     */
    public void setItemBrandname(String itemBrandname) {
        this.itemBrandname = itemBrandname == null ? null : itemBrandname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_item_brand.item_flag
     *
     * @return the value of t_bd_item_brand.item_flag
     *
     * @mbggenerated
     */
    public String getItemFlag() {
        return itemFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_item_brand.item_flag
     *
     * @param itemFlag the value for t_bd_item_brand.item_flag
     *
     * @mbggenerated
     */
    public void setItemFlag(String itemFlag) {
        this.itemFlag = itemFlag == null ? null : itemFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_item_brand.brand_parent
     *
     * @return the value of t_bd_item_brand.brand_parent
     *
     * @mbggenerated
     */
    public String getBrandParent() {
        return brandParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_item_brand.brand_parent
     *
     * @param brandParent the value for t_bd_item_brand.brand_parent
     *
     * @mbggenerated
     */
    public void setBrandParent(String brandParent) {
        this.brandParent = brandParent == null ? null : brandParent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_item_brand.display_flag
     *
     * @return the value of t_bd_item_brand.display_flag
     *
     * @mbggenerated
     */
    public String getDisplayFlag() {
        return displayFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_item_brand.display_flag
     *
     * @param displayFlag the value for t_bd_item_brand.display_flag
     *
     * @mbggenerated
     */
    public void setDisplayFlag(String displayFlag) {
        this.displayFlag = displayFlag == null ? null : displayFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_item_brand.return_rate
     *
     * @return the value of t_bd_item_brand.return_rate
     *
     * @mbggenerated
     */
    public BigDecimal getReturnRate() {
        return returnRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_item_brand.return_rate
     *
     * @param returnRate the value for t_bd_item_brand.return_rate
     *
     * @mbggenerated
     */
    public void setReturnRate(BigDecimal returnRate) {
        this.returnRate = returnRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_item_brand.comp_rate
     *
     * @return the value of t_bd_item_brand.comp_rate
     *
     * @mbggenerated
     */
    public BigDecimal getCompRate() {
        return compRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_item_brand.comp_rate
     *
     * @param compRate the value for t_bd_item_brand.comp_rate
     *
     * @mbggenerated
     */
    public void setCompRate(BigDecimal compRate) {
        this.compRate = compRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_item_brand.trans_flag
     *
     * @return the value of t_bd_item_brand.trans_flag
     *
     * @mbggenerated
     */
    public String getTransFlag() {
        return transFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_item_brand.trans_flag
     *
     * @param transFlag the value for t_bd_item_brand.trans_flag
     *
     * @mbggenerated
     */
    public void setTransFlag(String transFlag) {
        this.transFlag = transFlag == null ? null : transFlag.trim();
    }
}