package com.gd.datachx.entity;

import java.math.BigDecimal;
import java.util.Date;

public class TBdItemInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_item_info.item_no
     *
     * @mbggenerated
     */
    private String itemNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_item_info.item_subno
     *
     * @mbggenerated
     */
    private String itemSubno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_item_info.item_name
     *
     * @mbggenerated
     */
    private String itemName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_item_info.item_subname
     *
     * @mbggenerated
     */
    private String itemSubname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_item_info.item_clsno
     *
     * @mbggenerated
     */
    private String itemClsno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_item_info.item_brand
     *
     * @mbggenerated
     */
    private String itemBrand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_item_info.item_brandname
     *
     * @mbggenerated
     */
    private String itemBrandname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_item_info.unit_no
     *
     * @mbggenerated
     */
    private String unitNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_item_info.item_size
     *
     * @mbggenerated
     */
    private String itemSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_item_info.price
     *
     * @mbggenerated
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_item_info.base_price
     *
     * @mbggenerated
     */
    private BigDecimal basePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_item_info.sale_price
     *
     * @mbggenerated
     */
    private BigDecimal salePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_item_info.combine_sta
     *
     * @mbggenerated
     */
    private String combineSta;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_item_info.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_item_info.display_flag
     *
     * @mbggenerated
     */
    private String displayFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_item_info.po_cycle
     *
     * @mbggenerated
     */
    private Integer poCycle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_item_info.so_cycle
     *
     * @mbggenerated
     */
    private Integer soCycle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_item_info.automin_flag
     *
     * @mbggenerated
     */
    private String autominFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_item_info.en_dis
     *
     * @mbggenerated
     */
    private String enDis;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_item_info.change_price
     *
     * @mbggenerated
     */
    private String changePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_item_info.purchase_tax
     *
     * @mbggenerated
     */
    private BigDecimal purchaseTax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_item_info.sale_tax
     *
     * @mbggenerated
     */
    private BigDecimal saleTax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_item_info.purchase_spec
     *
     * @mbggenerated
     */
    private BigDecimal purchaseSpec;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_item_info.shipment_spec
     *
     * @mbggenerated
     */
    private BigDecimal shipmentSpec;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_item_info.item_supcust
     *
     * @mbggenerated
     */
    private String itemSupcust;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_item_info.main_supcust
     *
     * @mbggenerated
     */
    private String mainSupcust;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_item_info.item_stock
     *
     * @mbggenerated
     */
    private String itemStock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_item_info.build_date
     *
     * @mbggenerated
     */
    private Date buildDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_item_info.modify_date
     *
     * @mbggenerated
     */
    private Date modifyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_item_info.stop_date
     *
     * @mbggenerated
     */
    private Date stopDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_item_info.abc
     *
     * @mbggenerated
     */
    private String abc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_item_info.branch_price
     *
     * @mbggenerated
     */
    private String branchPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_item_info.item_rem
     *
     * @mbggenerated
     */
    private String itemRem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_item_info.vip_price
     *
     * @mbggenerated
     */
    private BigDecimal vipPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_item_info.sale_min_price
     *
     * @mbggenerated
     */
    private BigDecimal saleMinPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_item_info.com_flag
     *
     * @mbggenerated
     */
    private String comFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_item_info.vip_acc_flag
     *
     * @mbggenerated
     */
    private String vipAccFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_item_info.vip_acc_num
     *
     * @mbggenerated
     */
    private BigDecimal vipAccNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_item_info.dpfm_type
     *
     * @mbggenerated
     */
    private String dpfmType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_item_info.return_rate
     *
     * @mbggenerated
     */
    private BigDecimal returnRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_item_info.update_date
     *
     * @mbggenerated
     */
    private String updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_item_info.pro_code1
     *
     * @mbggenerated
     */
    private String proCode1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_item_info.pro_code2
     *
     * @mbggenerated
     */
    private String proCode2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_item_info.pro_code3
     *
     * @mbggenerated
     */
    private String proCode3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_item_info.pro_code4
     *
     * @mbggenerated
     */
    private String proCode4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_item_info.pro_code5
     *
     * @mbggenerated
     */
    private String proCode5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_item_info.pro_code6
     *
     * @mbggenerated
     */
    private String proCode6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_item_info.item_picture
     *
     * @mbggenerated
     */
    private String itemPicture;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_item_info.sale_flag
     *
     * @mbggenerated
     */
    private String saleFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_item_info.scheme_price
     *
     * @mbggenerated
     */
    private BigDecimal schemePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_item_info.vip_price2
     *
     * @mbggenerated
     */
    private BigDecimal vipPrice2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_item_info.vip_price3
     *
     * @mbggenerated
     */
    private BigDecimal vipPrice3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_item_info.vip_price4
     *
     * @mbggenerated
     */
    private BigDecimal vipPrice4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_item_info.vip_price5
     *
     * @mbggenerated
     */
    private BigDecimal vipPrice5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_item_info.valid_days
     *
     * @mbggenerated
     */
    private BigDecimal validDays;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_item_info.memo
     *
     * @mbggenerated
     */
    private String memo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_item_info.item_com
     *
     * @mbggenerated
     */
    private String itemCom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_item_info.product_area
     *
     * @mbggenerated
     */
    private String productArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_item_info.measure_flag
     *
     * @mbggenerated
     */
    private String measureFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_item_info.item_sup_flag
     *
     * @mbggenerated
     */
    private String itemSupFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_item_info.sup_rate
     *
     * @mbggenerated
     */
    private BigDecimal supRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_item_info.picture_type
     *
     * @mbggenerated
     */
    private String pictureType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_item_info.base_price1
     *
     * @mbggenerated
     */
    private BigDecimal basePrice1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_item_info.base_price2
     *
     * @mbggenerated
     */
    private BigDecimal basePrice2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_item_info.base_price3
     *
     * @mbggenerated
     */
    private BigDecimal basePrice3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_item_info.base_price4
     *
     * @mbggenerated
     */
    private BigDecimal basePrice4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_item_info.base_price5
     *
     * @mbggenerated
     */
    private BigDecimal basePrice5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_item_info.base_price6
     *
     * @mbggenerated
     */
    private BigDecimal basePrice6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_item_info.base_price7
     *
     * @mbggenerated
     */
    private BigDecimal basePrice7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_item_info.base_price8
     *
     * @mbggenerated
     */
    private BigDecimal basePrice8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_item_info.new_oper_id
     *
     * @mbggenerated
     */
    private String newOperId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_item_info.modify_oper_id
     *
     * @mbggenerated
     */
    private String modifyOperId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_item_info.en_gift
     *
     * @mbggenerated
     */
    private String enGift;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_item_info.promote_flag
     *
     * @mbggenerated
     */
    private String promoteFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_item_info.allow_flag
     *
     * @mbggenerated
     */
    private String allowFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_item_info.hand_flag
     *
     * @mbggenerated
     */
    private String handFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_item_info.alert_day1
     *
     * @mbggenerated
     */
    private Integer alertDay1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_item_info.alert_day2
     *
     * @mbggenerated
     */
    private Integer alertDay2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_item_info.item_no
     *
     * @return the value of t_bd_item_info.item_no
     *
     * @mbggenerated
     */
    public String getItemNo() {
        return itemNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_item_info.item_no
     *
     * @param itemNo the value for t_bd_item_info.item_no
     *
     * @mbggenerated
     */
    public void setItemNo(String itemNo) {
        this.itemNo = itemNo == null ? null : itemNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_item_info.item_subno
     *
     * @return the value of t_bd_item_info.item_subno
     *
     * @mbggenerated
     */
    public String getItemSubno() {
        return itemSubno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_item_info.item_subno
     *
     * @param itemSubno the value for t_bd_item_info.item_subno
     *
     * @mbggenerated
     */
    public void setItemSubno(String itemSubno) {
        this.itemSubno = itemSubno == null ? null : itemSubno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_item_info.item_name
     *
     * @return the value of t_bd_item_info.item_name
     *
     * @mbggenerated
     */
    public String getItemName() {
        return itemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_item_info.item_name
     *
     * @param itemName the value for t_bd_item_info.item_name
     *
     * @mbggenerated
     */
    public void setItemName(String itemName) {
        this.itemName = itemName == null ? null : itemName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_item_info.item_subname
     *
     * @return the value of t_bd_item_info.item_subname
     *
     * @mbggenerated
     */
    public String getItemSubname() {
        return itemSubname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_item_info.item_subname
     *
     * @param itemSubname the value for t_bd_item_info.item_subname
     *
     * @mbggenerated
     */
    public void setItemSubname(String itemSubname) {
        this.itemSubname = itemSubname == null ? null : itemSubname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_item_info.item_clsno
     *
     * @return the value of t_bd_item_info.item_clsno
     *
     * @mbggenerated
     */
    public String getItemClsno() {
        return itemClsno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_item_info.item_clsno
     *
     * @param itemClsno the value for t_bd_item_info.item_clsno
     *
     * @mbggenerated
     */
    public void setItemClsno(String itemClsno) {
        this.itemClsno = itemClsno == null ? null : itemClsno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_item_info.item_brand
     *
     * @return the value of t_bd_item_info.item_brand
     *
     * @mbggenerated
     */
    public String getItemBrand() {
        return itemBrand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_item_info.item_brand
     *
     * @param itemBrand the value for t_bd_item_info.item_brand
     *
     * @mbggenerated
     */
    public void setItemBrand(String itemBrand) {
        this.itemBrand = itemBrand == null ? null : itemBrand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_item_info.item_brandname
     *
     * @return the value of t_bd_item_info.item_brandname
     *
     * @mbggenerated
     */
    public String getItemBrandname() {
        return itemBrandname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_item_info.item_brandname
     *
     * @param itemBrandname the value for t_bd_item_info.item_brandname
     *
     * @mbggenerated
     */
    public void setItemBrandname(String itemBrandname) {
        this.itemBrandname = itemBrandname == null ? null : itemBrandname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_item_info.unit_no
     *
     * @return the value of t_bd_item_info.unit_no
     *
     * @mbggenerated
     */
    public String getUnitNo() {
        return unitNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_item_info.unit_no
     *
     * @param unitNo the value for t_bd_item_info.unit_no
     *
     * @mbggenerated
     */
    public void setUnitNo(String unitNo) {
        this.unitNo = unitNo == null ? null : unitNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_item_info.item_size
     *
     * @return the value of t_bd_item_info.item_size
     *
     * @mbggenerated
     */
    public String getItemSize() {
        return itemSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_item_info.item_size
     *
     * @param itemSize the value for t_bd_item_info.item_size
     *
     * @mbggenerated
     */
    public void setItemSize(String itemSize) {
        this.itemSize = itemSize == null ? null : itemSize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_item_info.price
     *
     * @return the value of t_bd_item_info.price
     *
     * @mbggenerated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_item_info.price
     *
     * @param price the value for t_bd_item_info.price
     *
     * @mbggenerated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_item_info.base_price
     *
     * @return the value of t_bd_item_info.base_price
     *
     * @mbggenerated
     */
    public BigDecimal getBasePrice() {
        return basePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_item_info.base_price
     *
     * @param basePrice the value for t_bd_item_info.base_price
     *
     * @mbggenerated
     */
    public void setBasePrice(BigDecimal basePrice) {
        this.basePrice = basePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_item_info.sale_price
     *
     * @return the value of t_bd_item_info.sale_price
     *
     * @mbggenerated
     */
    public BigDecimal getSalePrice() {
        return salePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_item_info.sale_price
     *
     * @param salePrice the value for t_bd_item_info.sale_price
     *
     * @mbggenerated
     */
    public void setSalePrice(BigDecimal salePrice) {
        this.salePrice = salePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_item_info.combine_sta
     *
     * @return the value of t_bd_item_info.combine_sta
     *
     * @mbggenerated
     */
    public String getCombineSta() {
        return combineSta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_item_info.combine_sta
     *
     * @param combineSta the value for t_bd_item_info.combine_sta
     *
     * @mbggenerated
     */
    public void setCombineSta(String combineSta) {
        this.combineSta = combineSta == null ? null : combineSta.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_item_info.status
     *
     * @return the value of t_bd_item_info.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_item_info.status
     *
     * @param status the value for t_bd_item_info.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_item_info.display_flag
     *
     * @return the value of t_bd_item_info.display_flag
     *
     * @mbggenerated
     */
    public String getDisplayFlag() {
        return displayFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_item_info.display_flag
     *
     * @param displayFlag the value for t_bd_item_info.display_flag
     *
     * @mbggenerated
     */
    public void setDisplayFlag(String displayFlag) {
        this.displayFlag = displayFlag == null ? null : displayFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_item_info.po_cycle
     *
     * @return the value of t_bd_item_info.po_cycle
     *
     * @mbggenerated
     */
    public Integer getPoCycle() {
        return poCycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_item_info.po_cycle
     *
     * @param poCycle the value for t_bd_item_info.po_cycle
     *
     * @mbggenerated
     */
    public void setPoCycle(Integer poCycle) {
        this.poCycle = poCycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_item_info.so_cycle
     *
     * @return the value of t_bd_item_info.so_cycle
     *
     * @mbggenerated
     */
    public Integer getSoCycle() {
        return soCycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_item_info.so_cycle
     *
     * @param soCycle the value for t_bd_item_info.so_cycle
     *
     * @mbggenerated
     */
    public void setSoCycle(Integer soCycle) {
        this.soCycle = soCycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_item_info.automin_flag
     *
     * @return the value of t_bd_item_info.automin_flag
     *
     * @mbggenerated
     */
    public String getAutominFlag() {
        return autominFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_item_info.automin_flag
     *
     * @param autominFlag the value for t_bd_item_info.automin_flag
     *
     * @mbggenerated
     */
    public void setAutominFlag(String autominFlag) {
        this.autominFlag = autominFlag == null ? null : autominFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_item_info.en_dis
     *
     * @return the value of t_bd_item_info.en_dis
     *
     * @mbggenerated
     */
    public String getEnDis() {
        return enDis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_item_info.en_dis
     *
     * @param enDis the value for t_bd_item_info.en_dis
     *
     * @mbggenerated
     */
    public void setEnDis(String enDis) {
        this.enDis = enDis == null ? null : enDis.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_item_info.change_price
     *
     * @return the value of t_bd_item_info.change_price
     *
     * @mbggenerated
     */
    public String getChangePrice() {
        return changePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_item_info.change_price
     *
     * @param changePrice the value for t_bd_item_info.change_price
     *
     * @mbggenerated
     */
    public void setChangePrice(String changePrice) {
        this.changePrice = changePrice == null ? null : changePrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_item_info.purchase_tax
     *
     * @return the value of t_bd_item_info.purchase_tax
     *
     * @mbggenerated
     */
    public BigDecimal getPurchaseTax() {
        return purchaseTax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_item_info.purchase_tax
     *
     * @param purchaseTax the value for t_bd_item_info.purchase_tax
     *
     * @mbggenerated
     */
    public void setPurchaseTax(BigDecimal purchaseTax) {
        this.purchaseTax = purchaseTax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_item_info.sale_tax
     *
     * @return the value of t_bd_item_info.sale_tax
     *
     * @mbggenerated
     */
    public BigDecimal getSaleTax() {
        return saleTax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_item_info.sale_tax
     *
     * @param saleTax the value for t_bd_item_info.sale_tax
     *
     * @mbggenerated
     */
    public void setSaleTax(BigDecimal saleTax) {
        this.saleTax = saleTax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_item_info.purchase_spec
     *
     * @return the value of t_bd_item_info.purchase_spec
     *
     * @mbggenerated
     */
    public BigDecimal getPurchaseSpec() {
        return purchaseSpec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_item_info.purchase_spec
     *
     * @param purchaseSpec the value for t_bd_item_info.purchase_spec
     *
     * @mbggenerated
     */
    public void setPurchaseSpec(BigDecimal purchaseSpec) {
        this.purchaseSpec = purchaseSpec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_item_info.shipment_spec
     *
     * @return the value of t_bd_item_info.shipment_spec
     *
     * @mbggenerated
     */
    public BigDecimal getShipmentSpec() {
        return shipmentSpec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_item_info.shipment_spec
     *
     * @param shipmentSpec the value for t_bd_item_info.shipment_spec
     *
     * @mbggenerated
     */
    public void setShipmentSpec(BigDecimal shipmentSpec) {
        this.shipmentSpec = shipmentSpec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_item_info.item_supcust
     *
     * @return the value of t_bd_item_info.item_supcust
     *
     * @mbggenerated
     */
    public String getItemSupcust() {
        return itemSupcust;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_item_info.item_supcust
     *
     * @param itemSupcust the value for t_bd_item_info.item_supcust
     *
     * @mbggenerated
     */
    public void setItemSupcust(String itemSupcust) {
        this.itemSupcust = itemSupcust == null ? null : itemSupcust.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_item_info.main_supcust
     *
     * @return the value of t_bd_item_info.main_supcust
     *
     * @mbggenerated
     */
    public String getMainSupcust() {
        return mainSupcust;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_item_info.main_supcust
     *
     * @param mainSupcust the value for t_bd_item_info.main_supcust
     *
     * @mbggenerated
     */
    public void setMainSupcust(String mainSupcust) {
        this.mainSupcust = mainSupcust == null ? null : mainSupcust.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_item_info.item_stock
     *
     * @return the value of t_bd_item_info.item_stock
     *
     * @mbggenerated
     */
    public String getItemStock() {
        return itemStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_item_info.item_stock
     *
     * @param itemStock the value for t_bd_item_info.item_stock
     *
     * @mbggenerated
     */
    public void setItemStock(String itemStock) {
        this.itemStock = itemStock == null ? null : itemStock.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_item_info.build_date
     *
     * @return the value of t_bd_item_info.build_date
     *
     * @mbggenerated
     */
    public Date getBuildDate() {
        return buildDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_item_info.build_date
     *
     * @param buildDate the value for t_bd_item_info.build_date
     *
     * @mbggenerated
     */
    public void setBuildDate(Date buildDate) {
        this.buildDate = buildDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_item_info.modify_date
     *
     * @return the value of t_bd_item_info.modify_date
     *
     * @mbggenerated
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_item_info.modify_date
     *
     * @param modifyDate the value for t_bd_item_info.modify_date
     *
     * @mbggenerated
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_item_info.stop_date
     *
     * @return the value of t_bd_item_info.stop_date
     *
     * @mbggenerated
     */
    public Date getStopDate() {
        return stopDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_item_info.stop_date
     *
     * @param stopDate the value for t_bd_item_info.stop_date
     *
     * @mbggenerated
     */
    public void setStopDate(Date stopDate) {
        this.stopDate = stopDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_item_info.abc
     *
     * @return the value of t_bd_item_info.abc
     *
     * @mbggenerated
     */
    public String getAbc() {
        return abc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_item_info.abc
     *
     * @param abc the value for t_bd_item_info.abc
     *
     * @mbggenerated
     */
    public void setAbc(String abc) {
        this.abc = abc == null ? null : abc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_item_info.branch_price
     *
     * @return the value of t_bd_item_info.branch_price
     *
     * @mbggenerated
     */
    public String getBranchPrice() {
        return branchPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_item_info.branch_price
     *
     * @param branchPrice the value for t_bd_item_info.branch_price
     *
     * @mbggenerated
     */
    public void setBranchPrice(String branchPrice) {
        this.branchPrice = branchPrice == null ? null : branchPrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_item_info.item_rem
     *
     * @return the value of t_bd_item_info.item_rem
     *
     * @mbggenerated
     */
    public String getItemRem() {
        return itemRem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_item_info.item_rem
     *
     * @param itemRem the value for t_bd_item_info.item_rem
     *
     * @mbggenerated
     */
    public void setItemRem(String itemRem) {
        this.itemRem = itemRem == null ? null : itemRem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_item_info.vip_price
     *
     * @return the value of t_bd_item_info.vip_price
     *
     * @mbggenerated
     */
    public BigDecimal getVipPrice() {
        return vipPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_item_info.vip_price
     *
     * @param vipPrice the value for t_bd_item_info.vip_price
     *
     * @mbggenerated
     */
    public void setVipPrice(BigDecimal vipPrice) {
        this.vipPrice = vipPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_item_info.sale_min_price
     *
     * @return the value of t_bd_item_info.sale_min_price
     *
     * @mbggenerated
     */
    public BigDecimal getSaleMinPrice() {
        return saleMinPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_item_info.sale_min_price
     *
     * @param saleMinPrice the value for t_bd_item_info.sale_min_price
     *
     * @mbggenerated
     */
    public void setSaleMinPrice(BigDecimal saleMinPrice) {
        this.saleMinPrice = saleMinPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_item_info.com_flag
     *
     * @return the value of t_bd_item_info.com_flag
     *
     * @mbggenerated
     */
    public String getComFlag() {
        return comFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_item_info.com_flag
     *
     * @param comFlag the value for t_bd_item_info.com_flag
     *
     * @mbggenerated
     */
    public void setComFlag(String comFlag) {
        this.comFlag = comFlag == null ? null : comFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_item_info.vip_acc_flag
     *
     * @return the value of t_bd_item_info.vip_acc_flag
     *
     * @mbggenerated
     */
    public String getVipAccFlag() {
        return vipAccFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_item_info.vip_acc_flag
     *
     * @param vipAccFlag the value for t_bd_item_info.vip_acc_flag
     *
     * @mbggenerated
     */
    public void setVipAccFlag(String vipAccFlag) {
        this.vipAccFlag = vipAccFlag == null ? null : vipAccFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_item_info.vip_acc_num
     *
     * @return the value of t_bd_item_info.vip_acc_num
     *
     * @mbggenerated
     */
    public BigDecimal getVipAccNum() {
        return vipAccNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_item_info.vip_acc_num
     *
     * @param vipAccNum the value for t_bd_item_info.vip_acc_num
     *
     * @mbggenerated
     */
    public void setVipAccNum(BigDecimal vipAccNum) {
        this.vipAccNum = vipAccNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_item_info.dpfm_type
     *
     * @return the value of t_bd_item_info.dpfm_type
     *
     * @mbggenerated
     */
    public String getDpfmType() {
        return dpfmType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_item_info.dpfm_type
     *
     * @param dpfmType the value for t_bd_item_info.dpfm_type
     *
     * @mbggenerated
     */
    public void setDpfmType(String dpfmType) {
        this.dpfmType = dpfmType == null ? null : dpfmType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_item_info.return_rate
     *
     * @return the value of t_bd_item_info.return_rate
     *
     * @mbggenerated
     */
    public BigDecimal getReturnRate() {
        return returnRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_item_info.return_rate
     *
     * @param returnRate the value for t_bd_item_info.return_rate
     *
     * @mbggenerated
     */
    public void setReturnRate(BigDecimal returnRate) {
        this.returnRate = returnRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_item_info.update_date
     *
     * @return the value of t_bd_item_info.update_date
     *
     * @mbggenerated
     */
    public String getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_item_info.update_date
     *
     * @param updateDate the value for t_bd_item_info.update_date
     *
     * @mbggenerated
     */
    public void setUpdateDate(String updateDate) {
        this.updateDate = updateDate == null ? null : updateDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_item_info.pro_code1
     *
     * @return the value of t_bd_item_info.pro_code1
     *
     * @mbggenerated
     */
    public String getProCode1() {
        return proCode1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_item_info.pro_code1
     *
     * @param proCode1 the value for t_bd_item_info.pro_code1
     *
     * @mbggenerated
     */
    public void setProCode1(String proCode1) {
        this.proCode1 = proCode1 == null ? null : proCode1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_item_info.pro_code2
     *
     * @return the value of t_bd_item_info.pro_code2
     *
     * @mbggenerated
     */
    public String getProCode2() {
        return proCode2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_item_info.pro_code2
     *
     * @param proCode2 the value for t_bd_item_info.pro_code2
     *
     * @mbggenerated
     */
    public void setProCode2(String proCode2) {
        this.proCode2 = proCode2 == null ? null : proCode2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_item_info.pro_code3
     *
     * @return the value of t_bd_item_info.pro_code3
     *
     * @mbggenerated
     */
    public String getProCode3() {
        return proCode3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_item_info.pro_code3
     *
     * @param proCode3 the value for t_bd_item_info.pro_code3
     *
     * @mbggenerated
     */
    public void setProCode3(String proCode3) {
        this.proCode3 = proCode3 == null ? null : proCode3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_item_info.pro_code4
     *
     * @return the value of t_bd_item_info.pro_code4
     *
     * @mbggenerated
     */
    public String getProCode4() {
        return proCode4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_item_info.pro_code4
     *
     * @param proCode4 the value for t_bd_item_info.pro_code4
     *
     * @mbggenerated
     */
    public void setProCode4(String proCode4) {
        this.proCode4 = proCode4 == null ? null : proCode4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_item_info.pro_code5
     *
     * @return the value of t_bd_item_info.pro_code5
     *
     * @mbggenerated
     */
    public String getProCode5() {
        return proCode5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_item_info.pro_code5
     *
     * @param proCode5 the value for t_bd_item_info.pro_code5
     *
     * @mbggenerated
     */
    public void setProCode5(String proCode5) {
        this.proCode5 = proCode5 == null ? null : proCode5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_item_info.pro_code6
     *
     * @return the value of t_bd_item_info.pro_code6
     *
     * @mbggenerated
     */
    public String getProCode6() {
        return proCode6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_item_info.pro_code6
     *
     * @param proCode6 the value for t_bd_item_info.pro_code6
     *
     * @mbggenerated
     */
    public void setProCode6(String proCode6) {
        this.proCode6 = proCode6 == null ? null : proCode6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_item_info.item_picture
     *
     * @return the value of t_bd_item_info.item_picture
     *
     * @mbggenerated
     */
    public String getItemPicture() {
        return itemPicture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_item_info.item_picture
     *
     * @param itemPicture the value for t_bd_item_info.item_picture
     *
     * @mbggenerated
     */
    public void setItemPicture(String itemPicture) {
        this.itemPicture = itemPicture == null ? null : itemPicture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_item_info.sale_flag
     *
     * @return the value of t_bd_item_info.sale_flag
     *
     * @mbggenerated
     */
    public String getSaleFlag() {
        return saleFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_item_info.sale_flag
     *
     * @param saleFlag the value for t_bd_item_info.sale_flag
     *
     * @mbggenerated
     */
    public void setSaleFlag(String saleFlag) {
        this.saleFlag = saleFlag == null ? null : saleFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_item_info.scheme_price
     *
     * @return the value of t_bd_item_info.scheme_price
     *
     * @mbggenerated
     */
    public BigDecimal getSchemePrice() {
        return schemePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_item_info.scheme_price
     *
     * @param schemePrice the value for t_bd_item_info.scheme_price
     *
     * @mbggenerated
     */
    public void setSchemePrice(BigDecimal schemePrice) {
        this.schemePrice = schemePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_item_info.vip_price2
     *
     * @return the value of t_bd_item_info.vip_price2
     *
     * @mbggenerated
     */
    public BigDecimal getVipPrice2() {
        return vipPrice2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_item_info.vip_price2
     *
     * @param vipPrice2 the value for t_bd_item_info.vip_price2
     *
     * @mbggenerated
     */
    public void setVipPrice2(BigDecimal vipPrice2) {
        this.vipPrice2 = vipPrice2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_item_info.vip_price3
     *
     * @return the value of t_bd_item_info.vip_price3
     *
     * @mbggenerated
     */
    public BigDecimal getVipPrice3() {
        return vipPrice3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_item_info.vip_price3
     *
     * @param vipPrice3 the value for t_bd_item_info.vip_price3
     *
     * @mbggenerated
     */
    public void setVipPrice3(BigDecimal vipPrice3) {
        this.vipPrice3 = vipPrice3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_item_info.vip_price4
     *
     * @return the value of t_bd_item_info.vip_price4
     *
     * @mbggenerated
     */
    public BigDecimal getVipPrice4() {
        return vipPrice4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_item_info.vip_price4
     *
     * @param vipPrice4 the value for t_bd_item_info.vip_price4
     *
     * @mbggenerated
     */
    public void setVipPrice4(BigDecimal vipPrice4) {
        this.vipPrice4 = vipPrice4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_item_info.vip_price5
     *
     * @return the value of t_bd_item_info.vip_price5
     *
     * @mbggenerated
     */
    public BigDecimal getVipPrice5() {
        return vipPrice5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_item_info.vip_price5
     *
     * @param vipPrice5 the value for t_bd_item_info.vip_price5
     *
     * @mbggenerated
     */
    public void setVipPrice5(BigDecimal vipPrice5) {
        this.vipPrice5 = vipPrice5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_item_info.valid_days
     *
     * @return the value of t_bd_item_info.valid_days
     *
     * @mbggenerated
     */
    public BigDecimal getValidDays() {
        return validDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_item_info.valid_days
     *
     * @param validDays the value for t_bd_item_info.valid_days
     *
     * @mbggenerated
     */
    public void setValidDays(BigDecimal validDays) {
        this.validDays = validDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_item_info.memo
     *
     * @return the value of t_bd_item_info.memo
     *
     * @mbggenerated
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_item_info.memo
     *
     * @param memo the value for t_bd_item_info.memo
     *
     * @mbggenerated
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_item_info.item_com
     *
     * @return the value of t_bd_item_info.item_com
     *
     * @mbggenerated
     */
    public String getItemCom() {
        return itemCom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_item_info.item_com
     *
     * @param itemCom the value for t_bd_item_info.item_com
     *
     * @mbggenerated
     */
    public void setItemCom(String itemCom) {
        this.itemCom = itemCom == null ? null : itemCom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_item_info.product_area
     *
     * @return the value of t_bd_item_info.product_area
     *
     * @mbggenerated
     */
    public String getProductArea() {
        return productArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_item_info.product_area
     *
     * @param productArea the value for t_bd_item_info.product_area
     *
     * @mbggenerated
     */
    public void setProductArea(String productArea) {
        this.productArea = productArea == null ? null : productArea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_item_info.measure_flag
     *
     * @return the value of t_bd_item_info.measure_flag
     *
     * @mbggenerated
     */
    public String getMeasureFlag() {
        return measureFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_item_info.measure_flag
     *
     * @param measureFlag the value for t_bd_item_info.measure_flag
     *
     * @mbggenerated
     */
    public void setMeasureFlag(String measureFlag) {
        this.measureFlag = measureFlag == null ? null : measureFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_item_info.item_sup_flag
     *
     * @return the value of t_bd_item_info.item_sup_flag
     *
     * @mbggenerated
     */
    public String getItemSupFlag() {
        return itemSupFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_item_info.item_sup_flag
     *
     * @param itemSupFlag the value for t_bd_item_info.item_sup_flag
     *
     * @mbggenerated
     */
    public void setItemSupFlag(String itemSupFlag) {
        this.itemSupFlag = itemSupFlag == null ? null : itemSupFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_item_info.sup_rate
     *
     * @return the value of t_bd_item_info.sup_rate
     *
     * @mbggenerated
     */
    public BigDecimal getSupRate() {
        return supRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_item_info.sup_rate
     *
     * @param supRate the value for t_bd_item_info.sup_rate
     *
     * @mbggenerated
     */
    public void setSupRate(BigDecimal supRate) {
        this.supRate = supRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_item_info.picture_type
     *
     * @return the value of t_bd_item_info.picture_type
     *
     * @mbggenerated
     */
    public String getPictureType() {
        return pictureType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_item_info.picture_type
     *
     * @param pictureType the value for t_bd_item_info.picture_type
     *
     * @mbggenerated
     */
    public void setPictureType(String pictureType) {
        this.pictureType = pictureType == null ? null : pictureType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_item_info.base_price1
     *
     * @return the value of t_bd_item_info.base_price1
     *
     * @mbggenerated
     */
    public BigDecimal getBasePrice1() {
        return basePrice1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_item_info.base_price1
     *
     * @param basePrice1 the value for t_bd_item_info.base_price1
     *
     * @mbggenerated
     */
    public void setBasePrice1(BigDecimal basePrice1) {
        this.basePrice1 = basePrice1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_item_info.base_price2
     *
     * @return the value of t_bd_item_info.base_price2
     *
     * @mbggenerated
     */
    public BigDecimal getBasePrice2() {
        return basePrice2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_item_info.base_price2
     *
     * @param basePrice2 the value for t_bd_item_info.base_price2
     *
     * @mbggenerated
     */
    public void setBasePrice2(BigDecimal basePrice2) {
        this.basePrice2 = basePrice2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_item_info.base_price3
     *
     * @return the value of t_bd_item_info.base_price3
     *
     * @mbggenerated
     */
    public BigDecimal getBasePrice3() {
        return basePrice3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_item_info.base_price3
     *
     * @param basePrice3 the value for t_bd_item_info.base_price3
     *
     * @mbggenerated
     */
    public void setBasePrice3(BigDecimal basePrice3) {
        this.basePrice3 = basePrice3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_item_info.base_price4
     *
     * @return the value of t_bd_item_info.base_price4
     *
     * @mbggenerated
     */
    public BigDecimal getBasePrice4() {
        return basePrice4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_item_info.base_price4
     *
     * @param basePrice4 the value for t_bd_item_info.base_price4
     *
     * @mbggenerated
     */
    public void setBasePrice4(BigDecimal basePrice4) {
        this.basePrice4 = basePrice4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_item_info.base_price5
     *
     * @return the value of t_bd_item_info.base_price5
     *
     * @mbggenerated
     */
    public BigDecimal getBasePrice5() {
        return basePrice5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_item_info.base_price5
     *
     * @param basePrice5 the value for t_bd_item_info.base_price5
     *
     * @mbggenerated
     */
    public void setBasePrice5(BigDecimal basePrice5) {
        this.basePrice5 = basePrice5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_item_info.base_price6
     *
     * @return the value of t_bd_item_info.base_price6
     *
     * @mbggenerated
     */
    public BigDecimal getBasePrice6() {
        return basePrice6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_item_info.base_price6
     *
     * @param basePrice6 the value for t_bd_item_info.base_price6
     *
     * @mbggenerated
     */
    public void setBasePrice6(BigDecimal basePrice6) {
        this.basePrice6 = basePrice6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_item_info.base_price7
     *
     * @return the value of t_bd_item_info.base_price7
     *
     * @mbggenerated
     */
    public BigDecimal getBasePrice7() {
        return basePrice7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_item_info.base_price7
     *
     * @param basePrice7 the value for t_bd_item_info.base_price7
     *
     * @mbggenerated
     */
    public void setBasePrice7(BigDecimal basePrice7) {
        this.basePrice7 = basePrice7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_item_info.base_price8
     *
     * @return the value of t_bd_item_info.base_price8
     *
     * @mbggenerated
     */
    public BigDecimal getBasePrice8() {
        return basePrice8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_item_info.base_price8
     *
     * @param basePrice8 the value for t_bd_item_info.base_price8
     *
     * @mbggenerated
     */
    public void setBasePrice8(BigDecimal basePrice8) {
        this.basePrice8 = basePrice8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_item_info.new_oper_id
     *
     * @return the value of t_bd_item_info.new_oper_id
     *
     * @mbggenerated
     */
    public String getNewOperId() {
        return newOperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_item_info.new_oper_id
     *
     * @param newOperId the value for t_bd_item_info.new_oper_id
     *
     * @mbggenerated
     */
    public void setNewOperId(String newOperId) {
        this.newOperId = newOperId == null ? null : newOperId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_item_info.modify_oper_id
     *
     * @return the value of t_bd_item_info.modify_oper_id
     *
     * @mbggenerated
     */
    public String getModifyOperId() {
        return modifyOperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_item_info.modify_oper_id
     *
     * @param modifyOperId the value for t_bd_item_info.modify_oper_id
     *
     * @mbggenerated
     */
    public void setModifyOperId(String modifyOperId) {
        this.modifyOperId = modifyOperId == null ? null : modifyOperId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_item_info.en_gift
     *
     * @return the value of t_bd_item_info.en_gift
     *
     * @mbggenerated
     */
    public String getEnGift() {
        return enGift;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_item_info.en_gift
     *
     * @param enGift the value for t_bd_item_info.en_gift
     *
     * @mbggenerated
     */
    public void setEnGift(String enGift) {
        this.enGift = enGift == null ? null : enGift.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_item_info.promote_flag
     *
     * @return the value of t_bd_item_info.promote_flag
     *
     * @mbggenerated
     */
    public String getPromoteFlag() {
        return promoteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_item_info.promote_flag
     *
     * @param promoteFlag the value for t_bd_item_info.promote_flag
     *
     * @mbggenerated
     */
    public void setPromoteFlag(String promoteFlag) {
        this.promoteFlag = promoteFlag == null ? null : promoteFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_item_info.allow_flag
     *
     * @return the value of t_bd_item_info.allow_flag
     *
     * @mbggenerated
     */
    public String getAllowFlag() {
        return allowFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_item_info.allow_flag
     *
     * @param allowFlag the value for t_bd_item_info.allow_flag
     *
     * @mbggenerated
     */
    public void setAllowFlag(String allowFlag) {
        this.allowFlag = allowFlag == null ? null : allowFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_item_info.hand_flag
     *
     * @return the value of t_bd_item_info.hand_flag
     *
     * @mbggenerated
     */
    public String getHandFlag() {
        return handFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_item_info.hand_flag
     *
     * @param handFlag the value for t_bd_item_info.hand_flag
     *
     * @mbggenerated
     */
    public void setHandFlag(String handFlag) {
        this.handFlag = handFlag == null ? null : handFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_item_info.alert_day1
     *
     * @return the value of t_bd_item_info.alert_day1
     *
     * @mbggenerated
     */
    public Integer getAlertDay1() {
        return alertDay1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_item_info.alert_day1
     *
     * @param alertDay1 the value for t_bd_item_info.alert_day1
     *
     * @mbggenerated
     */
    public void setAlertDay1(Integer alertDay1) {
        this.alertDay1 = alertDay1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_item_info.alert_day2
     *
     * @return the value of t_bd_item_info.alert_day2
     *
     * @mbggenerated
     */
    public Integer getAlertDay2() {
        return alertDay2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_item_info.alert_day2
     *
     * @param alertDay2 the value for t_bd_item_info.alert_day2
     *
     * @mbggenerated
     */
    public void setAlertDay2(Integer alertDay2) {
        this.alertDay2 = alertDay2;
    }
}