package com.gd.datachx.entity;

import java.math.BigDecimal;
import java.util.Date;

public class TBdSupcustInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_supcust_info.supcust_no
     *
     * @mbggenerated
     */
    private String supcustNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_supcust_info.supcust_flag
     *
     * @mbggenerated
     */
    private String supcustFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_supcust_info.sup_name
     *
     * @mbggenerated
     */
    private String supName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_supcust_info.region_no
     *
     * @mbggenerated
     */
    private String regionNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_supcust_info.sup_type
     *
     * @mbggenerated
     */
    private String supType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_supcust_info.sup_man
     *
     * @mbggenerated
     */
    private String supMan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_supcust_info.sup_addr
     *
     * @mbggenerated
     */
    private String supAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_supcust_info.zip
     *
     * @mbggenerated
     */
    private String zip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_supcust_info.sup_email
     *
     * @mbggenerated
     */
    private String supEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_supcust_info.sup_tel
     *
     * @mbggenerated
     */
    private String supTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_supcust_info.sup_fax
     *
     * @mbggenerated
     */
    private String supFax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_supcust_info.sup_acct_back
     *
     * @mbggenerated
     */
    private String supAcctBack;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_supcust_info.sup_acct_no
     *
     * @mbggenerated
     */
    private String supAcctNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_supcust_info.sup_tax_no
     *
     * @mbggenerated
     */
    private String supTaxNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_supcust_info.display_flag
     *
     * @mbggenerated
     */
    private String displayFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_supcust_info.check_out_flag
     *
     * @mbggenerated
     */
    private String checkOutFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_supcust_info.check_out_date
     *
     * @mbggenerated
     */
    private Short checkOutDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_supcust_info.check_out_day
     *
     * @mbggenerated
     */
    private Short checkOutDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_supcust_info.credit_amt
     *
     * @mbggenerated
     */
    private BigDecimal creditAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_supcust_info.sub_no
     *
     * @mbggenerated
     */
    private String subNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_supcust_info.pay_flag
     *
     * @mbggenerated
     */
    private String payFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_supcust_info.order_flag
     *
     * @mbggenerated
     */
    private String orderFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_supcust_info.purchase_day
     *
     * @mbggenerated
     */
    private Integer purchaseDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_supcust_info.po_cycle
     *
     * @mbggenerated
     */
    private Integer poCycle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_supcust_info.acc_level
     *
     * @mbggenerated
     */
    private String accLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_supcust_info.reg_type
     *
     * @mbggenerated
     */
    private String regType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_supcust_info.oper_id
     *
     * @mbggenerated
     */
    private String operId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_supcust_info.purchase_week
     *
     * @mbggenerated
     */
    private String purchaseWeek;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_supcust_info.sale_way
     *
     * @mbggenerated
     */
    private String saleWay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_supcust_info.shopcard
     *
     * @mbggenerated
     */
    private String shopcard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_supcust_info.modify_date
     *
     * @mbggenerated
     */
    private Date modifyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_supcust_info.settle_branch
     *
     * @mbggenerated
     */
    private String settleBranch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_supcust_info.com_flag
     *
     * @mbggenerated
     */
    private String comFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_supcust_info.mobile
     *
     * @mbggenerated
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_supcust_info.discount
     *
     * @mbggenerated
     */
    private BigDecimal discount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_supcust_info.trans_flag
     *
     * @mbggenerated
     */
    private String transFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_supcust_info.vip_card_id
     *
     * @mbggenerated
     */
    private String vipCardId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_supcust_info.memo
     *
     * @mbggenerated
     */
    private String memo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_supcust_info.receive_management
     *
     * @mbggenerated
     */
    private String receiveManagement;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_supcust_info.mbranch_no
     *
     * @mbggenerated
     */
    private String mbranchNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bd_supcust_info.use_way
     *
     * @mbggenerated
     */
    private String useWay;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_supcust_info.supcust_no
     *
     * @return the value of t_bd_supcust_info.supcust_no
     *
     * @mbggenerated
     */
    public String getSupcustNo() {
        return supcustNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_supcust_info.supcust_no
     *
     * @param supcustNo the value for t_bd_supcust_info.supcust_no
     *
     * @mbggenerated
     */
    public void setSupcustNo(String supcustNo) {
        this.supcustNo = supcustNo == null ? null : supcustNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_supcust_info.supcust_flag
     *
     * @return the value of t_bd_supcust_info.supcust_flag
     *
     * @mbggenerated
     */
    public String getSupcustFlag() {
        return supcustFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_supcust_info.supcust_flag
     *
     * @param supcustFlag the value for t_bd_supcust_info.supcust_flag
     *
     * @mbggenerated
     */
    public void setSupcustFlag(String supcustFlag) {
        this.supcustFlag = supcustFlag == null ? null : supcustFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_supcust_info.sup_name
     *
     * @return the value of t_bd_supcust_info.sup_name
     *
     * @mbggenerated
     */
    public String getSupName() {
        return supName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_supcust_info.sup_name
     *
     * @param supName the value for t_bd_supcust_info.sup_name
     *
     * @mbggenerated
     */
    public void setSupName(String supName) {
        this.supName = supName == null ? null : supName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_supcust_info.region_no
     *
     * @return the value of t_bd_supcust_info.region_no
     *
     * @mbggenerated
     */
    public String getRegionNo() {
        return regionNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_supcust_info.region_no
     *
     * @param regionNo the value for t_bd_supcust_info.region_no
     *
     * @mbggenerated
     */
    public void setRegionNo(String regionNo) {
        this.regionNo = regionNo == null ? null : regionNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_supcust_info.sup_type
     *
     * @return the value of t_bd_supcust_info.sup_type
     *
     * @mbggenerated
     */
    public String getSupType() {
        return supType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_supcust_info.sup_type
     *
     * @param supType the value for t_bd_supcust_info.sup_type
     *
     * @mbggenerated
     */
    public void setSupType(String supType) {
        this.supType = supType == null ? null : supType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_supcust_info.sup_man
     *
     * @return the value of t_bd_supcust_info.sup_man
     *
     * @mbggenerated
     */
    public String getSupMan() {
        return supMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_supcust_info.sup_man
     *
     * @param supMan the value for t_bd_supcust_info.sup_man
     *
     * @mbggenerated
     */
    public void setSupMan(String supMan) {
        this.supMan = supMan == null ? null : supMan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_supcust_info.sup_addr
     *
     * @return the value of t_bd_supcust_info.sup_addr
     *
     * @mbggenerated
     */
    public String getSupAddr() {
        return supAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_supcust_info.sup_addr
     *
     * @param supAddr the value for t_bd_supcust_info.sup_addr
     *
     * @mbggenerated
     */
    public void setSupAddr(String supAddr) {
        this.supAddr = supAddr == null ? null : supAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_supcust_info.zip
     *
     * @return the value of t_bd_supcust_info.zip
     *
     * @mbggenerated
     */
    public String getZip() {
        return zip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_supcust_info.zip
     *
     * @param zip the value for t_bd_supcust_info.zip
     *
     * @mbggenerated
     */
    public void setZip(String zip) {
        this.zip = zip == null ? null : zip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_supcust_info.sup_email
     *
     * @return the value of t_bd_supcust_info.sup_email
     *
     * @mbggenerated
     */
    public String getSupEmail() {
        return supEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_supcust_info.sup_email
     *
     * @param supEmail the value for t_bd_supcust_info.sup_email
     *
     * @mbggenerated
     */
    public void setSupEmail(String supEmail) {
        this.supEmail = supEmail == null ? null : supEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_supcust_info.sup_tel
     *
     * @return the value of t_bd_supcust_info.sup_tel
     *
     * @mbggenerated
     */
    public String getSupTel() {
        return supTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_supcust_info.sup_tel
     *
     * @param supTel the value for t_bd_supcust_info.sup_tel
     *
     * @mbggenerated
     */
    public void setSupTel(String supTel) {
        this.supTel = supTel == null ? null : supTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_supcust_info.sup_fax
     *
     * @return the value of t_bd_supcust_info.sup_fax
     *
     * @mbggenerated
     */
    public String getSupFax() {
        return supFax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_supcust_info.sup_fax
     *
     * @param supFax the value for t_bd_supcust_info.sup_fax
     *
     * @mbggenerated
     */
    public void setSupFax(String supFax) {
        this.supFax = supFax == null ? null : supFax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_supcust_info.sup_acct_back
     *
     * @return the value of t_bd_supcust_info.sup_acct_back
     *
     * @mbggenerated
     */
    public String getSupAcctBack() {
        return supAcctBack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_supcust_info.sup_acct_back
     *
     * @param supAcctBack the value for t_bd_supcust_info.sup_acct_back
     *
     * @mbggenerated
     */
    public void setSupAcctBack(String supAcctBack) {
        this.supAcctBack = supAcctBack == null ? null : supAcctBack.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_supcust_info.sup_acct_no
     *
     * @return the value of t_bd_supcust_info.sup_acct_no
     *
     * @mbggenerated
     */
    public String getSupAcctNo() {
        return supAcctNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_supcust_info.sup_acct_no
     *
     * @param supAcctNo the value for t_bd_supcust_info.sup_acct_no
     *
     * @mbggenerated
     */
    public void setSupAcctNo(String supAcctNo) {
        this.supAcctNo = supAcctNo == null ? null : supAcctNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_supcust_info.sup_tax_no
     *
     * @return the value of t_bd_supcust_info.sup_tax_no
     *
     * @mbggenerated
     */
    public String getSupTaxNo() {
        return supTaxNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_supcust_info.sup_tax_no
     *
     * @param supTaxNo the value for t_bd_supcust_info.sup_tax_no
     *
     * @mbggenerated
     */
    public void setSupTaxNo(String supTaxNo) {
        this.supTaxNo = supTaxNo == null ? null : supTaxNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_supcust_info.display_flag
     *
     * @return the value of t_bd_supcust_info.display_flag
     *
     * @mbggenerated
     */
    public String getDisplayFlag() {
        return displayFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_supcust_info.display_flag
     *
     * @param displayFlag the value for t_bd_supcust_info.display_flag
     *
     * @mbggenerated
     */
    public void setDisplayFlag(String displayFlag) {
        this.displayFlag = displayFlag == null ? null : displayFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_supcust_info.check_out_flag
     *
     * @return the value of t_bd_supcust_info.check_out_flag
     *
     * @mbggenerated
     */
    public String getCheckOutFlag() {
        return checkOutFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_supcust_info.check_out_flag
     *
     * @param checkOutFlag the value for t_bd_supcust_info.check_out_flag
     *
     * @mbggenerated
     */
    public void setCheckOutFlag(String checkOutFlag) {
        this.checkOutFlag = checkOutFlag == null ? null : checkOutFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_supcust_info.check_out_date
     *
     * @return the value of t_bd_supcust_info.check_out_date
     *
     * @mbggenerated
     */
    public Short getCheckOutDate() {
        return checkOutDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_supcust_info.check_out_date
     *
     * @param checkOutDate the value for t_bd_supcust_info.check_out_date
     *
     * @mbggenerated
     */
    public void setCheckOutDate(Short checkOutDate) {
        this.checkOutDate = checkOutDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_supcust_info.check_out_day
     *
     * @return the value of t_bd_supcust_info.check_out_day
     *
     * @mbggenerated
     */
    public Short getCheckOutDay() {
        return checkOutDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_supcust_info.check_out_day
     *
     * @param checkOutDay the value for t_bd_supcust_info.check_out_day
     *
     * @mbggenerated
     */
    public void setCheckOutDay(Short checkOutDay) {
        this.checkOutDay = checkOutDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_supcust_info.credit_amt
     *
     * @return the value of t_bd_supcust_info.credit_amt
     *
     * @mbggenerated
     */
    public BigDecimal getCreditAmt() {
        return creditAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_supcust_info.credit_amt
     *
     * @param creditAmt the value for t_bd_supcust_info.credit_amt
     *
     * @mbggenerated
     */
    public void setCreditAmt(BigDecimal creditAmt) {
        this.creditAmt = creditAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_supcust_info.sub_no
     *
     * @return the value of t_bd_supcust_info.sub_no
     *
     * @mbggenerated
     */
    public String getSubNo() {
        return subNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_supcust_info.sub_no
     *
     * @param subNo the value for t_bd_supcust_info.sub_no
     *
     * @mbggenerated
     */
    public void setSubNo(String subNo) {
        this.subNo = subNo == null ? null : subNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_supcust_info.pay_flag
     *
     * @return the value of t_bd_supcust_info.pay_flag
     *
     * @mbggenerated
     */
    public String getPayFlag() {
        return payFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_supcust_info.pay_flag
     *
     * @param payFlag the value for t_bd_supcust_info.pay_flag
     *
     * @mbggenerated
     */
    public void setPayFlag(String payFlag) {
        this.payFlag = payFlag == null ? null : payFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_supcust_info.order_flag
     *
     * @return the value of t_bd_supcust_info.order_flag
     *
     * @mbggenerated
     */
    public String getOrderFlag() {
        return orderFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_supcust_info.order_flag
     *
     * @param orderFlag the value for t_bd_supcust_info.order_flag
     *
     * @mbggenerated
     */
    public void setOrderFlag(String orderFlag) {
        this.orderFlag = orderFlag == null ? null : orderFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_supcust_info.purchase_day
     *
     * @return the value of t_bd_supcust_info.purchase_day
     *
     * @mbggenerated
     */
    public Integer getPurchaseDay() {
        return purchaseDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_supcust_info.purchase_day
     *
     * @param purchaseDay the value for t_bd_supcust_info.purchase_day
     *
     * @mbggenerated
     */
    public void setPurchaseDay(Integer purchaseDay) {
        this.purchaseDay = purchaseDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_supcust_info.po_cycle
     *
     * @return the value of t_bd_supcust_info.po_cycle
     *
     * @mbggenerated
     */
    public Integer getPoCycle() {
        return poCycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_supcust_info.po_cycle
     *
     * @param poCycle the value for t_bd_supcust_info.po_cycle
     *
     * @mbggenerated
     */
    public void setPoCycle(Integer poCycle) {
        this.poCycle = poCycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_supcust_info.acc_level
     *
     * @return the value of t_bd_supcust_info.acc_level
     *
     * @mbggenerated
     */
    public String getAccLevel() {
        return accLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_supcust_info.acc_level
     *
     * @param accLevel the value for t_bd_supcust_info.acc_level
     *
     * @mbggenerated
     */
    public void setAccLevel(String accLevel) {
        this.accLevel = accLevel == null ? null : accLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_supcust_info.reg_type
     *
     * @return the value of t_bd_supcust_info.reg_type
     *
     * @mbggenerated
     */
    public String getRegType() {
        return regType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_supcust_info.reg_type
     *
     * @param regType the value for t_bd_supcust_info.reg_type
     *
     * @mbggenerated
     */
    public void setRegType(String regType) {
        this.regType = regType == null ? null : regType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_supcust_info.oper_id
     *
     * @return the value of t_bd_supcust_info.oper_id
     *
     * @mbggenerated
     */
    public String getOperId() {
        return operId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_supcust_info.oper_id
     *
     * @param operId the value for t_bd_supcust_info.oper_id
     *
     * @mbggenerated
     */
    public void setOperId(String operId) {
        this.operId = operId == null ? null : operId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_supcust_info.purchase_week
     *
     * @return the value of t_bd_supcust_info.purchase_week
     *
     * @mbggenerated
     */
    public String getPurchaseWeek() {
        return purchaseWeek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_supcust_info.purchase_week
     *
     * @param purchaseWeek the value for t_bd_supcust_info.purchase_week
     *
     * @mbggenerated
     */
    public void setPurchaseWeek(String purchaseWeek) {
        this.purchaseWeek = purchaseWeek == null ? null : purchaseWeek.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_supcust_info.sale_way
     *
     * @return the value of t_bd_supcust_info.sale_way
     *
     * @mbggenerated
     */
    public String getSaleWay() {
        return saleWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_supcust_info.sale_way
     *
     * @param saleWay the value for t_bd_supcust_info.sale_way
     *
     * @mbggenerated
     */
    public void setSaleWay(String saleWay) {
        this.saleWay = saleWay == null ? null : saleWay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_supcust_info.shopcard
     *
     * @return the value of t_bd_supcust_info.shopcard
     *
     * @mbggenerated
     */
    public String getShopcard() {
        return shopcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_supcust_info.shopcard
     *
     * @param shopcard the value for t_bd_supcust_info.shopcard
     *
     * @mbggenerated
     */
    public void setShopcard(String shopcard) {
        this.shopcard = shopcard == null ? null : shopcard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_supcust_info.modify_date
     *
     * @return the value of t_bd_supcust_info.modify_date
     *
     * @mbggenerated
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_supcust_info.modify_date
     *
     * @param modifyDate the value for t_bd_supcust_info.modify_date
     *
     * @mbggenerated
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_supcust_info.settle_branch
     *
     * @return the value of t_bd_supcust_info.settle_branch
     *
     * @mbggenerated
     */
    public String getSettleBranch() {
        return settleBranch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_supcust_info.settle_branch
     *
     * @param settleBranch the value for t_bd_supcust_info.settle_branch
     *
     * @mbggenerated
     */
    public void setSettleBranch(String settleBranch) {
        this.settleBranch = settleBranch == null ? null : settleBranch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_supcust_info.com_flag
     *
     * @return the value of t_bd_supcust_info.com_flag
     *
     * @mbggenerated
     */
    public String getComFlag() {
        return comFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_supcust_info.com_flag
     *
     * @param comFlag the value for t_bd_supcust_info.com_flag
     *
     * @mbggenerated
     */
    public void setComFlag(String comFlag) {
        this.comFlag = comFlag == null ? null : comFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_supcust_info.mobile
     *
     * @return the value of t_bd_supcust_info.mobile
     *
     * @mbggenerated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_supcust_info.mobile
     *
     * @param mobile the value for t_bd_supcust_info.mobile
     *
     * @mbggenerated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_supcust_info.discount
     *
     * @return the value of t_bd_supcust_info.discount
     *
     * @mbggenerated
     */
    public BigDecimal getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_supcust_info.discount
     *
     * @param discount the value for t_bd_supcust_info.discount
     *
     * @mbggenerated
     */
    public void setDiscount(BigDecimal discount) {
        this.discount = discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_supcust_info.trans_flag
     *
     * @return the value of t_bd_supcust_info.trans_flag
     *
     * @mbggenerated
     */
    public String getTransFlag() {
        return transFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_supcust_info.trans_flag
     *
     * @param transFlag the value for t_bd_supcust_info.trans_flag
     *
     * @mbggenerated
     */
    public void setTransFlag(String transFlag) {
        this.transFlag = transFlag == null ? null : transFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_supcust_info.vip_card_id
     *
     * @return the value of t_bd_supcust_info.vip_card_id
     *
     * @mbggenerated
     */
    public String getVipCardId() {
        return vipCardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_supcust_info.vip_card_id
     *
     * @param vipCardId the value for t_bd_supcust_info.vip_card_id
     *
     * @mbggenerated
     */
    public void setVipCardId(String vipCardId) {
        this.vipCardId = vipCardId == null ? null : vipCardId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_supcust_info.memo
     *
     * @return the value of t_bd_supcust_info.memo
     *
     * @mbggenerated
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_supcust_info.memo
     *
     * @param memo the value for t_bd_supcust_info.memo
     *
     * @mbggenerated
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_supcust_info.receive_management
     *
     * @return the value of t_bd_supcust_info.receive_management
     *
     * @mbggenerated
     */
    public String getReceiveManagement() {
        return receiveManagement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_supcust_info.receive_management
     *
     * @param receiveManagement the value for t_bd_supcust_info.receive_management
     *
     * @mbggenerated
     */
    public void setReceiveManagement(String receiveManagement) {
        this.receiveManagement = receiveManagement == null ? null : receiveManagement.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_supcust_info.mbranch_no
     *
     * @return the value of t_bd_supcust_info.mbranch_no
     *
     * @mbggenerated
     */
    public String getMbranchNo() {
        return mbranchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_supcust_info.mbranch_no
     *
     * @param mbranchNo the value for t_bd_supcust_info.mbranch_no
     *
     * @mbggenerated
     */
    public void setMbranchNo(String mbranchNo) {
        this.mbranchNo = mbranchNo == null ? null : mbranchNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bd_supcust_info.use_way
     *
     * @return the value of t_bd_supcust_info.use_way
     *
     * @mbggenerated
     */
    public String getUseWay() {
        return useWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bd_supcust_info.use_way
     *
     * @param useWay the value for t_bd_supcust_info.use_way
     *
     * @mbggenerated
     */
    public void setUseWay(String useWay) {
        this.useWay = useWay == null ? null : useWay.trim();
    }
}