package com.gd.datachx.entity;

import java.math.BigDecimal;
import java.util.Date;

public class TImBatch {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_im_batch.flow_id
     *
     * @mbggenerated
     */
    private Long flowId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_im_batch.branch_no
     *
     * @mbggenerated
     */
    private String branchNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_im_batch.batch_no
     *
     * @mbggenerated
     */
    private String batchNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_im_batch.ph
     *
     * @mbggenerated
     */
    private String ph;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_im_batch.item_no
     *
     * @mbggenerated
     */
    private String itemNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_im_batch.oper_date
     *
     * @mbggenerated
     */
    private Date operDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_im_batch.product_date
     *
     * @mbggenerated
     */
    private Date productDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_im_batch.in_qty
     *
     * @mbggenerated
     */
    private BigDecimal inQty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_im_batch.out_qty
     *
     * @mbggenerated
     */
    private BigDecimal outQty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_im_batch.settle_qty
     *
     * @mbggenerated
     */
    private BigDecimal settleQty;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_im_batch.flow_id
     *
     * @return the value of t_im_batch.flow_id
     *
     * @mbggenerated
     */
    public Long getFlowId() {
        return flowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_im_batch.flow_id
     *
     * @param flowId the value for t_im_batch.flow_id
     *
     * @mbggenerated
     */
    public void setFlowId(Long flowId) {
        this.flowId = flowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_im_batch.branch_no
     *
     * @return the value of t_im_batch.branch_no
     *
     * @mbggenerated
     */
    public String getBranchNo() {
        return branchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_im_batch.branch_no
     *
     * @param branchNo the value for t_im_batch.branch_no
     *
     * @mbggenerated
     */
    public void setBranchNo(String branchNo) {
        this.branchNo = branchNo == null ? null : branchNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_im_batch.batch_no
     *
     * @return the value of t_im_batch.batch_no
     *
     * @mbggenerated
     */
    public String getBatchNo() {
        return batchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_im_batch.batch_no
     *
     * @param batchNo the value for t_im_batch.batch_no
     *
     * @mbggenerated
     */
    public void setBatchNo(String batchNo) {
        this.batchNo = batchNo == null ? null : batchNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_im_batch.ph
     *
     * @return the value of t_im_batch.ph
     *
     * @mbggenerated
     */
    public String getPh() {
        return ph;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_im_batch.ph
     *
     * @param ph the value for t_im_batch.ph
     *
     * @mbggenerated
     */
    public void setPh(String ph) {
        this.ph = ph == null ? null : ph.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_im_batch.item_no
     *
     * @return the value of t_im_batch.item_no
     *
     * @mbggenerated
     */
    public String getItemNo() {
        return itemNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_im_batch.item_no
     *
     * @param itemNo the value for t_im_batch.item_no
     *
     * @mbggenerated
     */
    public void setItemNo(String itemNo) {
        this.itemNo = itemNo == null ? null : itemNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_im_batch.oper_date
     *
     * @return the value of t_im_batch.oper_date
     *
     * @mbggenerated
     */
    public Date getOperDate() {
        return operDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_im_batch.oper_date
     *
     * @param operDate the value for t_im_batch.oper_date
     *
     * @mbggenerated
     */
    public void setOperDate(Date operDate) {
        this.operDate = operDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_im_batch.product_date
     *
     * @return the value of t_im_batch.product_date
     *
     * @mbggenerated
     */
    public Date getProductDate() {
        return productDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_im_batch.product_date
     *
     * @param productDate the value for t_im_batch.product_date
     *
     * @mbggenerated
     */
    public void setProductDate(Date productDate) {
        this.productDate = productDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_im_batch.in_qty
     *
     * @return the value of t_im_batch.in_qty
     *
     * @mbggenerated
     */
    public BigDecimal getInQty() {
        return inQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_im_batch.in_qty
     *
     * @param inQty the value for t_im_batch.in_qty
     *
     * @mbggenerated
     */
    public void setInQty(BigDecimal inQty) {
        this.inQty = inQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_im_batch.out_qty
     *
     * @return the value of t_im_batch.out_qty
     *
     * @mbggenerated
     */
    public BigDecimal getOutQty() {
        return outQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_im_batch.out_qty
     *
     * @param outQty the value for t_im_batch.out_qty
     *
     * @mbggenerated
     */
    public void setOutQty(BigDecimal outQty) {
        this.outQty = outQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_im_batch.settle_qty
     *
     * @return the value of t_im_batch.settle_qty
     *
     * @mbggenerated
     */
    public BigDecimal getSettleQty() {
        return settleQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_im_batch.settle_qty
     *
     * @param settleQty the value for t_im_batch.settle_qty
     *
     * @mbggenerated
     */
    public void setSettleQty(BigDecimal settleQty) {
        this.settleQty = settleQty;
    }
}