package com.gd.datachx.entity;

import java.math.BigDecimal;
import java.util.Date;

public class TImBranchStock {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_im_branch_stock.item_no
     *
     * @mbggenerated
     */
    private String itemNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_im_branch_stock.branch_no
     *
     * @mbggenerated
     */
    private String branchNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_im_branch_stock.stock_qty
     *
     * @mbggenerated
     */
    private BigDecimal stockQty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_im_branch_stock.route_qty
     *
     * @mbggenerated
     */
    private BigDecimal routeQty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_im_branch_stock.avg_cost
     *
     * @mbggenerated
     */
    private BigDecimal avgCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_im_branch_stock.cost_amt
     *
     * @mbggenerated
     */
    private BigDecimal costAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_im_branch_stock.last_inprice
     *
     * @mbggenerated
     */
    private BigDecimal lastInprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_im_branch_stock.last_baseprice
     *
     * @mbggenerated
     */
    private BigDecimal lastBaseprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_im_branch_stock.min_qty
     *
     * @mbggenerated
     */
    private BigDecimal minQty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_im_branch_stock.max_qty
     *
     * @mbggenerated
     */
    private BigDecimal maxQty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_im_branch_stock.acc_qty
     *
     * @mbggenerated
     */
    private BigDecimal accQty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_im_branch_stock.oper_date
     *
     * @mbggenerated
     */
    private Date operDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_im_branch_stock.com_flag
     *
     * @mbggenerated
     */
    private String comFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_im_branch_stock.item_no
     *
     * @return the value of t_im_branch_stock.item_no
     *
     * @mbggenerated
     */
    public String getItemNo() {
        return itemNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_im_branch_stock.item_no
     *
     * @param itemNo the value for t_im_branch_stock.item_no
     *
     * @mbggenerated
     */
    public void setItemNo(String itemNo) {
        this.itemNo = itemNo == null ? null : itemNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_im_branch_stock.branch_no
     *
     * @return the value of t_im_branch_stock.branch_no
     *
     * @mbggenerated
     */
    public String getBranchNo() {
        return branchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_im_branch_stock.branch_no
     *
     * @param branchNo the value for t_im_branch_stock.branch_no
     *
     * @mbggenerated
     */
    public void setBranchNo(String branchNo) {
        this.branchNo = branchNo == null ? null : branchNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_im_branch_stock.stock_qty
     *
     * @return the value of t_im_branch_stock.stock_qty
     *
     * @mbggenerated
     */
    public BigDecimal getStockQty() {
        return stockQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_im_branch_stock.stock_qty
     *
     * @param stockQty the value for t_im_branch_stock.stock_qty
     *
     * @mbggenerated
     */
    public void setStockQty(BigDecimal stockQty) {
        this.stockQty = stockQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_im_branch_stock.route_qty
     *
     * @return the value of t_im_branch_stock.route_qty
     *
     * @mbggenerated
     */
    public BigDecimal getRouteQty() {
        return routeQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_im_branch_stock.route_qty
     *
     * @param routeQty the value for t_im_branch_stock.route_qty
     *
     * @mbggenerated
     */
    public void setRouteQty(BigDecimal routeQty) {
        this.routeQty = routeQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_im_branch_stock.avg_cost
     *
     * @return the value of t_im_branch_stock.avg_cost
     *
     * @mbggenerated
     */
    public BigDecimal getAvgCost() {
        return avgCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_im_branch_stock.avg_cost
     *
     * @param avgCost the value for t_im_branch_stock.avg_cost
     *
     * @mbggenerated
     */
    public void setAvgCost(BigDecimal avgCost) {
        this.avgCost = avgCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_im_branch_stock.cost_amt
     *
     * @return the value of t_im_branch_stock.cost_amt
     *
     * @mbggenerated
     */
    public BigDecimal getCostAmt() {
        return costAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_im_branch_stock.cost_amt
     *
     * @param costAmt the value for t_im_branch_stock.cost_amt
     *
     * @mbggenerated
     */
    public void setCostAmt(BigDecimal costAmt) {
        this.costAmt = costAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_im_branch_stock.last_inprice
     *
     * @return the value of t_im_branch_stock.last_inprice
     *
     * @mbggenerated
     */
    public BigDecimal getLastInprice() {
        return lastInprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_im_branch_stock.last_inprice
     *
     * @param lastInprice the value for t_im_branch_stock.last_inprice
     *
     * @mbggenerated
     */
    public void setLastInprice(BigDecimal lastInprice) {
        this.lastInprice = lastInprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_im_branch_stock.last_baseprice
     *
     * @return the value of t_im_branch_stock.last_baseprice
     *
     * @mbggenerated
     */
    public BigDecimal getLastBaseprice() {
        return lastBaseprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_im_branch_stock.last_baseprice
     *
     * @param lastBaseprice the value for t_im_branch_stock.last_baseprice
     *
     * @mbggenerated
     */
    public void setLastBaseprice(BigDecimal lastBaseprice) {
        this.lastBaseprice = lastBaseprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_im_branch_stock.min_qty
     *
     * @return the value of t_im_branch_stock.min_qty
     *
     * @mbggenerated
     */
    public BigDecimal getMinQty() {
        return minQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_im_branch_stock.min_qty
     *
     * @param minQty the value for t_im_branch_stock.min_qty
     *
     * @mbggenerated
     */
    public void setMinQty(BigDecimal minQty) {
        this.minQty = minQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_im_branch_stock.max_qty
     *
     * @return the value of t_im_branch_stock.max_qty
     *
     * @mbggenerated
     */
    public BigDecimal getMaxQty() {
        return maxQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_im_branch_stock.max_qty
     *
     * @param maxQty the value for t_im_branch_stock.max_qty
     *
     * @mbggenerated
     */
    public void setMaxQty(BigDecimal maxQty) {
        this.maxQty = maxQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_im_branch_stock.acc_qty
     *
     * @return the value of t_im_branch_stock.acc_qty
     *
     * @mbggenerated
     */
    public BigDecimal getAccQty() {
        return accQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_im_branch_stock.acc_qty
     *
     * @param accQty the value for t_im_branch_stock.acc_qty
     *
     * @mbggenerated
     */
    public void setAccQty(BigDecimal accQty) {
        this.accQty = accQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_im_branch_stock.oper_date
     *
     * @return the value of t_im_branch_stock.oper_date
     *
     * @mbggenerated
     */
    public Date getOperDate() {
        return operDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_im_branch_stock.oper_date
     *
     * @param operDate the value for t_im_branch_stock.oper_date
     *
     * @mbggenerated
     */
    public void setOperDate(Date operDate) {
        this.operDate = operDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_im_branch_stock.com_flag
     *
     * @return the value of t_im_branch_stock.com_flag
     *
     * @mbggenerated
     */
    public String getComFlag() {
        return comFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_im_branch_stock.com_flag
     *
     * @param comFlag the value for t_im_branch_stock.com_flag
     *
     * @mbggenerated
     */
    public void setComFlag(String comFlag) {
        this.comFlag = comFlag == null ? null : comFlag.trim();
    }
}