package com.gd.datachx.entity;

import java.math.BigDecimal;
import java.util.Date;

public class TRmPayflow {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_payflow.com_no
     *
     * @mbggenerated
     */
    private Long comNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_payflow.flow_id
     *
     * @mbggenerated
     */
    private Short flowId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_payflow.flow_no
     *
     * @mbggenerated
     */
    private String flowNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_payflow.sale_amount
     *
     * @mbggenerated
     */
    private BigDecimal saleAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_payflow.branch_no
     *
     * @mbggenerated
     */
    private String branchNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_payflow.pay_way
     *
     * @mbggenerated
     */
    private String payWay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_payflow.sell_way
     *
     * @mbggenerated
     */
    private String sellWay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_payflow.card_no
     *
     * @mbggenerated
     */
    private String cardNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_payflow.card_id
     *
     * @mbggenerated
     */
    private String cardId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_payflow.vip_no
     *
     * @mbggenerated
     */
    private String vipNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_payflow.coin_no
     *
     * @mbggenerated
     */
    private String coinNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_payflow.coin_rate
     *
     * @mbggenerated
     */
    private BigDecimal coinRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_payflow.pay_amount
     *
     * @mbggenerated
     */
    private BigDecimal payAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_payflow.oper_date
     *
     * @mbggenerated
     */
    private Date operDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_payflow.oper_id
     *
     * @mbggenerated
     */
    private String operId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_payflow.counter_no
     *
     * @mbggenerated
     */
    private String counterNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_payflow.sale_man
     *
     * @mbggenerated
     */
    private String saleMan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_payflow.cashier_no
     *
     * @mbggenerated
     */
    private String cashierNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_payflow.memo
     *
     * @mbggenerated
     */
    private String memo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_payflow.voucher_no
     *
     * @mbggenerated
     */
    private String voucherNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_payflow.shift_no
     *
     * @mbggenerated
     */
    private String shiftNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_payflow.com_flag
     *
     * @mbggenerated
     */
    private String comFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_payflow.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_payflow.rdm_no
     *
     * @mbggenerated
     */
    private String rdmNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_payflow.com_no
     *
     * @return the value of t_rm_payflow.com_no
     *
     * @mbggenerated
     */
    public Long getComNo() {
        return comNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_payflow.com_no
     *
     * @param comNo the value for t_rm_payflow.com_no
     *
     * @mbggenerated
     */
    public void setComNo(Long comNo) {
        this.comNo = comNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_payflow.flow_id
     *
     * @return the value of t_rm_payflow.flow_id
     *
     * @mbggenerated
     */
    public Short getFlowId() {
        return flowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_payflow.flow_id
     *
     * @param flowId the value for t_rm_payflow.flow_id
     *
     * @mbggenerated
     */
    public void setFlowId(Short flowId) {
        this.flowId = flowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_payflow.flow_no
     *
     * @return the value of t_rm_payflow.flow_no
     *
     * @mbggenerated
     */
    public String getFlowNo() {
        return flowNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_payflow.flow_no
     *
     * @param flowNo the value for t_rm_payflow.flow_no
     *
     * @mbggenerated
     */
    public void setFlowNo(String flowNo) {
        this.flowNo = flowNo == null ? null : flowNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_payflow.sale_amount
     *
     * @return the value of t_rm_payflow.sale_amount
     *
     * @mbggenerated
     */
    public BigDecimal getSaleAmount() {
        return saleAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_payflow.sale_amount
     *
     * @param saleAmount the value for t_rm_payflow.sale_amount
     *
     * @mbggenerated
     */
    public void setSaleAmount(BigDecimal saleAmount) {
        this.saleAmount = saleAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_payflow.branch_no
     *
     * @return the value of t_rm_payflow.branch_no
     *
     * @mbggenerated
     */
    public String getBranchNo() {
        return branchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_payflow.branch_no
     *
     * @param branchNo the value for t_rm_payflow.branch_no
     *
     * @mbggenerated
     */
    public void setBranchNo(String branchNo) {
        this.branchNo = branchNo == null ? null : branchNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_payflow.pay_way
     *
     * @return the value of t_rm_payflow.pay_way
     *
     * @mbggenerated
     */
    public String getPayWay() {
        return payWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_payflow.pay_way
     *
     * @param payWay the value for t_rm_payflow.pay_way
     *
     * @mbggenerated
     */
    public void setPayWay(String payWay) {
        this.payWay = payWay == null ? null : payWay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_payflow.sell_way
     *
     * @return the value of t_rm_payflow.sell_way
     *
     * @mbggenerated
     */
    public String getSellWay() {
        return sellWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_payflow.sell_way
     *
     * @param sellWay the value for t_rm_payflow.sell_way
     *
     * @mbggenerated
     */
    public void setSellWay(String sellWay) {
        this.sellWay = sellWay == null ? null : sellWay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_payflow.card_no
     *
     * @return the value of t_rm_payflow.card_no
     *
     * @mbggenerated
     */
    public String getCardNo() {
        return cardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_payflow.card_no
     *
     * @param cardNo the value for t_rm_payflow.card_no
     *
     * @mbggenerated
     */
    public void setCardNo(String cardNo) {
        this.cardNo = cardNo == null ? null : cardNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_payflow.card_id
     *
     * @return the value of t_rm_payflow.card_id
     *
     * @mbggenerated
     */
    public String getCardId() {
        return cardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_payflow.card_id
     *
     * @param cardId the value for t_rm_payflow.card_id
     *
     * @mbggenerated
     */
    public void setCardId(String cardId) {
        this.cardId = cardId == null ? null : cardId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_payflow.vip_no
     *
     * @return the value of t_rm_payflow.vip_no
     *
     * @mbggenerated
     */
    public String getVipNo() {
        return vipNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_payflow.vip_no
     *
     * @param vipNo the value for t_rm_payflow.vip_no
     *
     * @mbggenerated
     */
    public void setVipNo(String vipNo) {
        this.vipNo = vipNo == null ? null : vipNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_payflow.coin_no
     *
     * @return the value of t_rm_payflow.coin_no
     *
     * @mbggenerated
     */
    public String getCoinNo() {
        return coinNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_payflow.coin_no
     *
     * @param coinNo the value for t_rm_payflow.coin_no
     *
     * @mbggenerated
     */
    public void setCoinNo(String coinNo) {
        this.coinNo = coinNo == null ? null : coinNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_payflow.coin_rate
     *
     * @return the value of t_rm_payflow.coin_rate
     *
     * @mbggenerated
     */
    public BigDecimal getCoinRate() {
        return coinRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_payflow.coin_rate
     *
     * @param coinRate the value for t_rm_payflow.coin_rate
     *
     * @mbggenerated
     */
    public void setCoinRate(BigDecimal coinRate) {
        this.coinRate = coinRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_payflow.pay_amount
     *
     * @return the value of t_rm_payflow.pay_amount
     *
     * @mbggenerated
     */
    public BigDecimal getPayAmount() {
        return payAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_payflow.pay_amount
     *
     * @param payAmount the value for t_rm_payflow.pay_amount
     *
     * @mbggenerated
     */
    public void setPayAmount(BigDecimal payAmount) {
        this.payAmount = payAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_payflow.oper_date
     *
     * @return the value of t_rm_payflow.oper_date
     *
     * @mbggenerated
     */
    public Date getOperDate() {
        return operDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_payflow.oper_date
     *
     * @param operDate the value for t_rm_payflow.oper_date
     *
     * @mbggenerated
     */
    public void setOperDate(Date operDate) {
        this.operDate = operDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_payflow.oper_id
     *
     * @return the value of t_rm_payflow.oper_id
     *
     * @mbggenerated
     */
    public String getOperId() {
        return operId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_payflow.oper_id
     *
     * @param operId the value for t_rm_payflow.oper_id
     *
     * @mbggenerated
     */
    public void setOperId(String operId) {
        this.operId = operId == null ? null : operId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_payflow.counter_no
     *
     * @return the value of t_rm_payflow.counter_no
     *
     * @mbggenerated
     */
    public String getCounterNo() {
        return counterNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_payflow.counter_no
     *
     * @param counterNo the value for t_rm_payflow.counter_no
     *
     * @mbggenerated
     */
    public void setCounterNo(String counterNo) {
        this.counterNo = counterNo == null ? null : counterNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_payflow.sale_man
     *
     * @return the value of t_rm_payflow.sale_man
     *
     * @mbggenerated
     */
    public String getSaleMan() {
        return saleMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_payflow.sale_man
     *
     * @param saleMan the value for t_rm_payflow.sale_man
     *
     * @mbggenerated
     */
    public void setSaleMan(String saleMan) {
        this.saleMan = saleMan == null ? null : saleMan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_payflow.cashier_no
     *
     * @return the value of t_rm_payflow.cashier_no
     *
     * @mbggenerated
     */
    public String getCashierNo() {
        return cashierNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_payflow.cashier_no
     *
     * @param cashierNo the value for t_rm_payflow.cashier_no
     *
     * @mbggenerated
     */
    public void setCashierNo(String cashierNo) {
        this.cashierNo = cashierNo == null ? null : cashierNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_payflow.memo
     *
     * @return the value of t_rm_payflow.memo
     *
     * @mbggenerated
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_payflow.memo
     *
     * @param memo the value for t_rm_payflow.memo
     *
     * @mbggenerated
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_payflow.voucher_no
     *
     * @return the value of t_rm_payflow.voucher_no
     *
     * @mbggenerated
     */
    public String getVoucherNo() {
        return voucherNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_payflow.voucher_no
     *
     * @param voucherNo the value for t_rm_payflow.voucher_no
     *
     * @mbggenerated
     */
    public void setVoucherNo(String voucherNo) {
        this.voucherNo = voucherNo == null ? null : voucherNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_payflow.shift_no
     *
     * @return the value of t_rm_payflow.shift_no
     *
     * @mbggenerated
     */
    public String getShiftNo() {
        return shiftNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_payflow.shift_no
     *
     * @param shiftNo the value for t_rm_payflow.shift_no
     *
     * @mbggenerated
     */
    public void setShiftNo(String shiftNo) {
        this.shiftNo = shiftNo == null ? null : shiftNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_payflow.com_flag
     *
     * @return the value of t_rm_payflow.com_flag
     *
     * @mbggenerated
     */
    public String getComFlag() {
        return comFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_payflow.com_flag
     *
     * @param comFlag the value for t_rm_payflow.com_flag
     *
     * @mbggenerated
     */
    public void setComFlag(String comFlag) {
        this.comFlag = comFlag == null ? null : comFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_payflow.remark
     *
     * @return the value of t_rm_payflow.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_payflow.remark
     *
     * @param remark the value for t_rm_payflow.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_payflow.rdm_no
     *
     * @return the value of t_rm_payflow.rdm_no
     *
     * @mbggenerated
     */
    public String getRdmNo() {
        return rdmNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_payflow.rdm_no
     *
     * @param rdmNo the value for t_rm_payflow.rdm_no
     *
     * @mbggenerated
     */
    public void setRdmNo(String rdmNo) {
        this.rdmNo = rdmNo == null ? null : rdmNo.trim();
    }
}