package com.gd.datachx.entity;

import java.math.BigDecimal;
import java.util.Date;

public class TRmSaleflow {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_saleflow.com_no
     *
     * @mbggenerated
     */
    private Long comNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_saleflow.flow_id
     *
     * @mbggenerated
     */
    private Short flowId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_saleflow.flow_no
     *
     * @mbggenerated
     */
    private String flowNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_saleflow.branch_no
     *
     * @mbggenerated
     */
    private String branchNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_saleflow.item_no
     *
     * @mbggenerated
     */
    private String itemNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_saleflow.source_price
     *
     * @mbggenerated
     */
    private BigDecimal sourcePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_saleflow.sale_price
     *
     * @mbggenerated
     */
    private BigDecimal salePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_saleflow.cost_price
     *
     * @mbggenerated
     */
    private BigDecimal costPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_saleflow.sale_qnty
     *
     * @mbggenerated
     */
    private BigDecimal saleQnty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_saleflow.sale_money
     *
     * @mbggenerated
     */
    private BigDecimal saleMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_saleflow.sell_way
     *
     * @mbggenerated
     */
    private String sellWay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_saleflow.oper_id
     *
     * @mbggenerated
     */
    private String operId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_saleflow.sale_man
     *
     * @mbggenerated
     */
    private String saleMan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_saleflow.oper_date
     *
     * @mbggenerated
     */
    private Date operDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_saleflow.shift_no
     *
     * @mbggenerated
     */
    private BigDecimal shiftNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_saleflow.com_flag
     *
     * @mbggenerated
     */
    private String comFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_saleflow.spec_flag
     *
     * @mbggenerated
     */
    private String specFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_saleflow.pref_amt
     *
     * @mbggenerated
     */
    private BigDecimal prefAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_saleflow.in_price
     *
     * @mbggenerated
     */
    private BigDecimal inPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_saleflow.acc_num
     *
     * @mbggenerated
     */
    private BigDecimal accNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_saleflow.dec_rate
     *
     * @mbggenerated
     */
    private BigDecimal decRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_saleflow.card_id
     *
     * @mbggenerated
     */
    private String cardId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_saleflow.card_no
     *
     * @mbggenerated
     */
    private String cardNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_saleflow.pro_id
     *
     * @mbggenerated
     */
    private Integer proId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_saleflow.clss_rate
     *
     * @mbggenerated
     */
    private BigDecimal clssRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_saleflow.Brand_rate
     *
     * @mbggenerated
     */
    private BigDecimal brandRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_saleflow.sale_rate
     *
     * @mbggenerated
     */
    private BigDecimal saleRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_saleflow.sale_duty_rate
     *
     * @mbggenerated
     */
    private BigDecimal saleDutyRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_saleflow.plan_no
     *
     * @mbggenerated
     */
    private String planNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_saleflow.serials_no
     *
     * @mbggenerated
     */
    private String serialsNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_saleflow.com_no
     *
     * @return the value of t_rm_saleflow.com_no
     *
     * @mbggenerated
     */
    public Long getComNo() {
        return comNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_saleflow.com_no
     *
     * @param comNo the value for t_rm_saleflow.com_no
     *
     * @mbggenerated
     */
    public void setComNo(Long comNo) {
        this.comNo = comNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_saleflow.flow_id
     *
     * @return the value of t_rm_saleflow.flow_id
     *
     * @mbggenerated
     */
    public Short getFlowId() {
        return flowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_saleflow.flow_id
     *
     * @param flowId the value for t_rm_saleflow.flow_id
     *
     * @mbggenerated
     */
    public void setFlowId(Short flowId) {
        this.flowId = flowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_saleflow.flow_no
     *
     * @return the value of t_rm_saleflow.flow_no
     *
     * @mbggenerated
     */
    public String getFlowNo() {
        return flowNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_saleflow.flow_no
     *
     * @param flowNo the value for t_rm_saleflow.flow_no
     *
     * @mbggenerated
     */
    public void setFlowNo(String flowNo) {
        this.flowNo = flowNo == null ? null : flowNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_saleflow.branch_no
     *
     * @return the value of t_rm_saleflow.branch_no
     *
     * @mbggenerated
     */
    public String getBranchNo() {
        return branchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_saleflow.branch_no
     *
     * @param branchNo the value for t_rm_saleflow.branch_no
     *
     * @mbggenerated
     */
    public void setBranchNo(String branchNo) {
        this.branchNo = branchNo == null ? null : branchNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_saleflow.item_no
     *
     * @return the value of t_rm_saleflow.item_no
     *
     * @mbggenerated
     */
    public String getItemNo() {
        return itemNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_saleflow.item_no
     *
     * @param itemNo the value for t_rm_saleflow.item_no
     *
     * @mbggenerated
     */
    public void setItemNo(String itemNo) {
        this.itemNo = itemNo == null ? null : itemNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_saleflow.source_price
     *
     * @return the value of t_rm_saleflow.source_price
     *
     * @mbggenerated
     */
    public BigDecimal getSourcePrice() {
        return sourcePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_saleflow.source_price
     *
     * @param sourcePrice the value for t_rm_saleflow.source_price
     *
     * @mbggenerated
     */
    public void setSourcePrice(BigDecimal sourcePrice) {
        this.sourcePrice = sourcePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_saleflow.sale_price
     *
     * @return the value of t_rm_saleflow.sale_price
     *
     * @mbggenerated
     */
    public BigDecimal getSalePrice() {
        return salePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_saleflow.sale_price
     *
     * @param salePrice the value for t_rm_saleflow.sale_price
     *
     * @mbggenerated
     */
    public void setSalePrice(BigDecimal salePrice) {
        this.salePrice = salePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_saleflow.cost_price
     *
     * @return the value of t_rm_saleflow.cost_price
     *
     * @mbggenerated
     */
    public BigDecimal getCostPrice() {
        return costPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_saleflow.cost_price
     *
     * @param costPrice the value for t_rm_saleflow.cost_price
     *
     * @mbggenerated
     */
    public void setCostPrice(BigDecimal costPrice) {
        this.costPrice = costPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_saleflow.sale_qnty
     *
     * @return the value of t_rm_saleflow.sale_qnty
     *
     * @mbggenerated
     */
    public BigDecimal getSaleQnty() {
        return saleQnty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_saleflow.sale_qnty
     *
     * @param saleQnty the value for t_rm_saleflow.sale_qnty
     *
     * @mbggenerated
     */
    public void setSaleQnty(BigDecimal saleQnty) {
        this.saleQnty = saleQnty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_saleflow.sale_money
     *
     * @return the value of t_rm_saleflow.sale_money
     *
     * @mbggenerated
     */
    public BigDecimal getSaleMoney() {
        return saleMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_saleflow.sale_money
     *
     * @param saleMoney the value for t_rm_saleflow.sale_money
     *
     * @mbggenerated
     */
    public void setSaleMoney(BigDecimal saleMoney) {
        this.saleMoney = saleMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_saleflow.sell_way
     *
     * @return the value of t_rm_saleflow.sell_way
     *
     * @mbggenerated
     */
    public String getSellWay() {
        return sellWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_saleflow.sell_way
     *
     * @param sellWay the value for t_rm_saleflow.sell_way
     *
     * @mbggenerated
     */
    public void setSellWay(String sellWay) {
        this.sellWay = sellWay == null ? null : sellWay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_saleflow.oper_id
     *
     * @return the value of t_rm_saleflow.oper_id
     *
     * @mbggenerated
     */
    public String getOperId() {
        return operId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_saleflow.oper_id
     *
     * @param operId the value for t_rm_saleflow.oper_id
     *
     * @mbggenerated
     */
    public void setOperId(String operId) {
        this.operId = operId == null ? null : operId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_saleflow.sale_man
     *
     * @return the value of t_rm_saleflow.sale_man
     *
     * @mbggenerated
     */
    public String getSaleMan() {
        return saleMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_saleflow.sale_man
     *
     * @param saleMan the value for t_rm_saleflow.sale_man
     *
     * @mbggenerated
     */
    public void setSaleMan(String saleMan) {
        this.saleMan = saleMan == null ? null : saleMan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_saleflow.oper_date
     *
     * @return the value of t_rm_saleflow.oper_date
     *
     * @mbggenerated
     */
    public Date getOperDate() {
        return operDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_saleflow.oper_date
     *
     * @param operDate the value for t_rm_saleflow.oper_date
     *
     * @mbggenerated
     */
    public void setOperDate(Date operDate) {
        this.operDate = operDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_saleflow.shift_no
     *
     * @return the value of t_rm_saleflow.shift_no
     *
     * @mbggenerated
     */
    public BigDecimal getShiftNo() {
        return shiftNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_saleflow.shift_no
     *
     * @param shiftNo the value for t_rm_saleflow.shift_no
     *
     * @mbggenerated
     */
    public void setShiftNo(BigDecimal shiftNo) {
        this.shiftNo = shiftNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_saleflow.com_flag
     *
     * @return the value of t_rm_saleflow.com_flag
     *
     * @mbggenerated
     */
    public String getComFlag() {
        return comFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_saleflow.com_flag
     *
     * @param comFlag the value for t_rm_saleflow.com_flag
     *
     * @mbggenerated
     */
    public void setComFlag(String comFlag) {
        this.comFlag = comFlag == null ? null : comFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_saleflow.spec_flag
     *
     * @return the value of t_rm_saleflow.spec_flag
     *
     * @mbggenerated
     */
    public String getSpecFlag() {
        return specFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_saleflow.spec_flag
     *
     * @param specFlag the value for t_rm_saleflow.spec_flag
     *
     * @mbggenerated
     */
    public void setSpecFlag(String specFlag) {
        this.specFlag = specFlag == null ? null : specFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_saleflow.pref_amt
     *
     * @return the value of t_rm_saleflow.pref_amt
     *
     * @mbggenerated
     */
    public BigDecimal getPrefAmt() {
        return prefAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_saleflow.pref_amt
     *
     * @param prefAmt the value for t_rm_saleflow.pref_amt
     *
     * @mbggenerated
     */
    public void setPrefAmt(BigDecimal prefAmt) {
        this.prefAmt = prefAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_saleflow.in_price
     *
     * @return the value of t_rm_saleflow.in_price
     *
     * @mbggenerated
     */
    public BigDecimal getInPrice() {
        return inPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_saleflow.in_price
     *
     * @param inPrice the value for t_rm_saleflow.in_price
     *
     * @mbggenerated
     */
    public void setInPrice(BigDecimal inPrice) {
        this.inPrice = inPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_saleflow.acc_num
     *
     * @return the value of t_rm_saleflow.acc_num
     *
     * @mbggenerated
     */
    public BigDecimal getAccNum() {
        return accNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_saleflow.acc_num
     *
     * @param accNum the value for t_rm_saleflow.acc_num
     *
     * @mbggenerated
     */
    public void setAccNum(BigDecimal accNum) {
        this.accNum = accNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_saleflow.dec_rate
     *
     * @return the value of t_rm_saleflow.dec_rate
     *
     * @mbggenerated
     */
    public BigDecimal getDecRate() {
        return decRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_saleflow.dec_rate
     *
     * @param decRate the value for t_rm_saleflow.dec_rate
     *
     * @mbggenerated
     */
    public void setDecRate(BigDecimal decRate) {
        this.decRate = decRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_saleflow.card_id
     *
     * @return the value of t_rm_saleflow.card_id
     *
     * @mbggenerated
     */
    public String getCardId() {
        return cardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_saleflow.card_id
     *
     * @param cardId the value for t_rm_saleflow.card_id
     *
     * @mbggenerated
     */
    public void setCardId(String cardId) {
        this.cardId = cardId == null ? null : cardId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_saleflow.card_no
     *
     * @return the value of t_rm_saleflow.card_no
     *
     * @mbggenerated
     */
    public String getCardNo() {
        return cardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_saleflow.card_no
     *
     * @param cardNo the value for t_rm_saleflow.card_no
     *
     * @mbggenerated
     */
    public void setCardNo(String cardNo) {
        this.cardNo = cardNo == null ? null : cardNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_saleflow.pro_id
     *
     * @return the value of t_rm_saleflow.pro_id
     *
     * @mbggenerated
     */
    public Integer getProId() {
        return proId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_saleflow.pro_id
     *
     * @param proId the value for t_rm_saleflow.pro_id
     *
     * @mbggenerated
     */
    public void setProId(Integer proId) {
        this.proId = proId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_saleflow.clss_rate
     *
     * @return the value of t_rm_saleflow.clss_rate
     *
     * @mbggenerated
     */
    public BigDecimal getClssRate() {
        return clssRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_saleflow.clss_rate
     *
     * @param clssRate the value for t_rm_saleflow.clss_rate
     *
     * @mbggenerated
     */
    public void setClssRate(BigDecimal clssRate) {
        this.clssRate = clssRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_saleflow.Brand_rate
     *
     * @return the value of t_rm_saleflow.Brand_rate
     *
     * @mbggenerated
     */
    public BigDecimal getBrandRate() {
        return brandRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_saleflow.Brand_rate
     *
     * @param brandRate the value for t_rm_saleflow.Brand_rate
     *
     * @mbggenerated
     */
    public void setBrandRate(BigDecimal brandRate) {
        this.brandRate = brandRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_saleflow.sale_rate
     *
     * @return the value of t_rm_saleflow.sale_rate
     *
     * @mbggenerated
     */
    public BigDecimal getSaleRate() {
        return saleRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_saleflow.sale_rate
     *
     * @param saleRate the value for t_rm_saleflow.sale_rate
     *
     * @mbggenerated
     */
    public void setSaleRate(BigDecimal saleRate) {
        this.saleRate = saleRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_saleflow.sale_duty_rate
     *
     * @return the value of t_rm_saleflow.sale_duty_rate
     *
     * @mbggenerated
     */
    public BigDecimal getSaleDutyRate() {
        return saleDutyRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_saleflow.sale_duty_rate
     *
     * @param saleDutyRate the value for t_rm_saleflow.sale_duty_rate
     *
     * @mbggenerated
     */
    public void setSaleDutyRate(BigDecimal saleDutyRate) {
        this.saleDutyRate = saleDutyRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_saleflow.plan_no
     *
     * @return the value of t_rm_saleflow.plan_no
     *
     * @mbggenerated
     */
    public String getPlanNo() {
        return planNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_saleflow.plan_no
     *
     * @param planNo the value for t_rm_saleflow.plan_no
     *
     * @mbggenerated
     */
    public void setPlanNo(String planNo) {
        this.planNo = planNo == null ? null : planNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_saleflow.serials_no
     *
     * @return the value of t_rm_saleflow.serials_no
     *
     * @mbggenerated
     */
    public String getSerialsNo() {
        return serialsNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_saleflow.serials_no
     *
     * @param serialsNo the value for t_rm_saleflow.serials_no
     *
     * @mbggenerated
     */
    public void setSerialsNo(String serialsNo) {
        this.serialsNo = serialsNo == null ? null : serialsNo.trim();
    }
}