package com.gd.datachx.entity;

import lombok.Data;

import java.math.BigDecimal;
import java.util.Date;

/**
 * @Auther: He Wenbo
 * @Date: 2019/7/7
 * @Description:
 */
@Data
public class TRmSaleFlowInfo {
    String posid;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_saleflow.com_no
     *
     * @mbggenerated
     */
    private Long comNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_saleflow.flow_id
     *
     * @mbggenerated
     */
    private Short flowId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_saleflow.flow_no
     *
     * @mbggenerated
     */
    private String flowNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_saleflow.branch_no
     *
     * @mbggenerated
     */
    private String branchNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_saleflow.item_no
     *
     * @mbggenerated
     */
    private String itemNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_saleflow.source_price
     *
     * @mbggenerated
     */
    private BigDecimal sourcePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_saleflow.sale_price
     *
     * @mbggenerated
     */
    private BigDecimal salePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_saleflow.cost_price
     *
     * @mbggenerated
     */
    private BigDecimal costPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_saleflow.sale_qnty
     *
     * @mbggenerated
     */
    private BigDecimal saleQnty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_saleflow.sale_money
     *
     * @mbggenerated
     */
    private BigDecimal saleMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_saleflow.sell_way
     *
     * @mbggenerated
     */
    private String sellWay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_saleflow.oper_id
     *
     * @mbggenerated
     */
    private String operId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_saleflow.sale_man
     *
     * @mbggenerated
     */
    private String saleMan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_saleflow.oper_date
     *
     * @mbggenerated
     */
    private Date operDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_saleflow.shift_no
     *
     * @mbggenerated
     */
    private BigDecimal shiftNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_saleflow.com_flag
     *
     * @mbggenerated
     */
    private String comFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_saleflow.spec_flag
     *
     * @mbggenerated
     */
    private String specFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_saleflow.pref_amt
     *
     * @mbggenerated
     */
    private BigDecimal prefAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_saleflow.in_price
     *
     * @mbggenerated
     */
    private BigDecimal inPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_saleflow.acc_num
     *
     * @mbggenerated
     */
    private BigDecimal accNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_saleflow.dec_rate
     *
     * @mbggenerated
     */
    private BigDecimal decRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_saleflow.card_id
     *
     * @mbggenerated
     */
    private String cardId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_saleflow.card_no
     *
     * @mbggenerated
     */
    private String cardNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_saleflow.pro_id
     *
     * @mbggenerated
     */
    private Integer proId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_saleflow.clss_rate
     *
     * @mbggenerated
     */
    private BigDecimal clssRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_saleflow.Brand_rate
     *
     * @mbggenerated
     */
    private BigDecimal brandRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_saleflow.sale_rate
     *
     * @mbggenerated
     */
    private BigDecimal saleRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_saleflow.sale_duty_rate
     *
     * @mbggenerated
     */
    private BigDecimal saleDutyRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_saleflow.plan_no
     *
     * @mbggenerated
     */
    private String planNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_saleflow.serials_no
     *
     * @mbggenerated
     */
    private String serialsNo;

}
