package com.gd.datachx.entity;

import java.math.BigDecimal;

public class TRmSaleman {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_saleman.branch_no
     *
     * @mbggenerated
     */
    private String branchNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_saleman.sale_id
     *
     * @mbggenerated
     */
    private String saleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_saleman.sale_name
     *
     * @mbggenerated
     */
    private String saleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_saleman.sale_status
     *
     * @mbggenerated
     */
    private String saleStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_saleman.memo
     *
     * @mbggenerated
     */
    private String memo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_saleman.return_rate
     *
     * @mbggenerated
     */
    private BigDecimal returnRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_saleman.sale_duty
     *
     * @mbggenerated
     */
    private String saleDuty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_saleman.sale_duty_rate
     *
     * @mbggenerated
     */
    private BigDecimal saleDutyRate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_saleman.branch_no
     *
     * @return the value of t_rm_saleman.branch_no
     *
     * @mbggenerated
     */
    public String getBranchNo() {
        return branchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_saleman.branch_no
     *
     * @param branchNo the value for t_rm_saleman.branch_no
     *
     * @mbggenerated
     */
    public void setBranchNo(String branchNo) {
        this.branchNo = branchNo == null ? null : branchNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_saleman.sale_id
     *
     * @return the value of t_rm_saleman.sale_id
     *
     * @mbggenerated
     */
    public String getSaleId() {
        return saleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_saleman.sale_id
     *
     * @param saleId the value for t_rm_saleman.sale_id
     *
     * @mbggenerated
     */
    public void setSaleId(String saleId) {
        this.saleId = saleId == null ? null : saleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_saleman.sale_name
     *
     * @return the value of t_rm_saleman.sale_name
     *
     * @mbggenerated
     */
    public String getSaleName() {
        return saleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_saleman.sale_name
     *
     * @param saleName the value for t_rm_saleman.sale_name
     *
     * @mbggenerated
     */
    public void setSaleName(String saleName) {
        this.saleName = saleName == null ? null : saleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_saleman.sale_status
     *
     * @return the value of t_rm_saleman.sale_status
     *
     * @mbggenerated
     */
    public String getSaleStatus() {
        return saleStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_saleman.sale_status
     *
     * @param saleStatus the value for t_rm_saleman.sale_status
     *
     * @mbggenerated
     */
    public void setSaleStatus(String saleStatus) {
        this.saleStatus = saleStatus == null ? null : saleStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_saleman.memo
     *
     * @return the value of t_rm_saleman.memo
     *
     * @mbggenerated
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_saleman.memo
     *
     * @param memo the value for t_rm_saleman.memo
     *
     * @mbggenerated
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_saleman.return_rate
     *
     * @return the value of t_rm_saleman.return_rate
     *
     * @mbggenerated
     */
    public BigDecimal getReturnRate() {
        return returnRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_saleman.return_rate
     *
     * @param returnRate the value for t_rm_saleman.return_rate
     *
     * @mbggenerated
     */
    public void setReturnRate(BigDecimal returnRate) {
        this.returnRate = returnRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_saleman.sale_duty
     *
     * @return the value of t_rm_saleman.sale_duty
     *
     * @mbggenerated
     */
    public String getSaleDuty() {
        return saleDuty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_saleman.sale_duty
     *
     * @param saleDuty the value for t_rm_saleman.sale_duty
     *
     * @mbggenerated
     */
    public void setSaleDuty(String saleDuty) {
        this.saleDuty = saleDuty == null ? null : saleDuty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_saleman.sale_duty_rate
     *
     * @return the value of t_rm_saleman.sale_duty_rate
     *
     * @mbggenerated
     */
    public BigDecimal getSaleDutyRate() {
        return saleDutyRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_saleman.sale_duty_rate
     *
     * @param saleDutyRate the value for t_rm_saleman.sale_duty_rate
     *
     * @mbggenerated
     */
    public void setSaleDutyRate(BigDecimal saleDutyRate) {
        this.saleDutyRate = saleDutyRate;
    }
}