package com.gd.datachx.entity;

import java.math.BigDecimal;
import java.util.Date;

public class TRmVipSavelist {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_vip_savelist.flow_id
     *
     * @mbggenerated
     */
    private Long flowId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_vip_savelist.card_id
     *
     * @mbggenerated
     */
    private String cardId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_vip_savelist.card_no
     *
     * @mbggenerated
     */
    private String cardNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_vip_savelist.card_type
     *
     * @mbggenerated
     */
    private String cardType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_vip_savelist.branch_no
     *
     * @mbggenerated
     */
    private String branchNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_vip_savelist.oper_type
     *
     * @mbggenerated
     */
    private String operType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_vip_savelist.oper_id
     *
     * @mbggenerated
     */
    private String operId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_vip_savelist.ope_date
     *
     * @mbggenerated
     */
    private Date opeDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_vip_savelist.flow_no
     *
     * @mbggenerated
     */
    private String flowNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_vip_savelist.consum_amt
     *
     * @mbggenerated
     */
    private BigDecimal consumAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_vip_savelist.acc_num
     *
     * @mbggenerated
     */
    private BigDecimal accNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_vip_savelist.new_cardno
     *
     * @mbggenerated
     */
    private String newCardno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_vip_savelist.oper_des
     *
     * @mbggenerated
     */
    private String operDes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_vip_savelist.memo
     *
     * @mbggenerated
     */
    private String memo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_vip_savelist.com_flag
     *
     * @mbggenerated
     */
    private String comFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_vip_savelist.sale_qty
     *
     * @mbggenerated
     */
    private BigDecimal saleQty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_vip_savelist.item_no
     *
     * @mbggenerated
     */
    private String itemNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_vip_savelist.real_amt
     *
     * @mbggenerated
     */
    private BigDecimal realAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_vip_savelist.payway
     *
     * @mbggenerated
     */
    private String payway;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_vip_savelist.other2
     *
     * @mbggenerated
     */
    private String other2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_vip_savelist.residue_amt
     *
     * @mbggenerated
     */
    private BigDecimal residueAmt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_vip_savelist.flow_id
     *
     * @return the value of t_rm_vip_savelist.flow_id
     *
     * @mbggenerated
     */
    public Long getFlowId() {
        return flowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_vip_savelist.flow_id
     *
     * @param flowId the value for t_rm_vip_savelist.flow_id
     *
     * @mbggenerated
     */
    public void setFlowId(Long flowId) {
        this.flowId = flowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_vip_savelist.card_id
     *
     * @return the value of t_rm_vip_savelist.card_id
     *
     * @mbggenerated
     */
    public String getCardId() {
        return cardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_vip_savelist.card_id
     *
     * @param cardId the value for t_rm_vip_savelist.card_id
     *
     * @mbggenerated
     */
    public void setCardId(String cardId) {
        this.cardId = cardId == null ? null : cardId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_vip_savelist.card_no
     *
     * @return the value of t_rm_vip_savelist.card_no
     *
     * @mbggenerated
     */
    public String getCardNo() {
        return cardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_vip_savelist.card_no
     *
     * @param cardNo the value for t_rm_vip_savelist.card_no
     *
     * @mbggenerated
     */
    public void setCardNo(String cardNo) {
        this.cardNo = cardNo == null ? null : cardNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_vip_savelist.card_type
     *
     * @return the value of t_rm_vip_savelist.card_type
     *
     * @mbggenerated
     */
    public String getCardType() {
        return cardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_vip_savelist.card_type
     *
     * @param cardType the value for t_rm_vip_savelist.card_type
     *
     * @mbggenerated
     */
    public void setCardType(String cardType) {
        this.cardType = cardType == null ? null : cardType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_vip_savelist.branch_no
     *
     * @return the value of t_rm_vip_savelist.branch_no
     *
     * @mbggenerated
     */
    public String getBranchNo() {
        return branchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_vip_savelist.branch_no
     *
     * @param branchNo the value for t_rm_vip_savelist.branch_no
     *
     * @mbggenerated
     */
    public void setBranchNo(String branchNo) {
        this.branchNo = branchNo == null ? null : branchNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_vip_savelist.oper_type
     *
     * @return the value of t_rm_vip_savelist.oper_type
     *
     * @mbggenerated
     */
    public String getOperType() {
        return operType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_vip_savelist.oper_type
     *
     * @param operType the value for t_rm_vip_savelist.oper_type
     *
     * @mbggenerated
     */
    public void setOperType(String operType) {
        this.operType = operType == null ? null : operType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_vip_savelist.oper_id
     *
     * @return the value of t_rm_vip_savelist.oper_id
     *
     * @mbggenerated
     */
    public String getOperId() {
        return operId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_vip_savelist.oper_id
     *
     * @param operId the value for t_rm_vip_savelist.oper_id
     *
     * @mbggenerated
     */
    public void setOperId(String operId) {
        this.operId = operId == null ? null : operId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_vip_savelist.ope_date
     *
     * @return the value of t_rm_vip_savelist.ope_date
     *
     * @mbggenerated
     */
    public Date getOpeDate() {
        return opeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_vip_savelist.ope_date
     *
     * @param opeDate the value for t_rm_vip_savelist.ope_date
     *
     * @mbggenerated
     */
    public void setOpeDate(Date opeDate) {
        this.opeDate = opeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_vip_savelist.flow_no
     *
     * @return the value of t_rm_vip_savelist.flow_no
     *
     * @mbggenerated
     */
    public String getFlowNo() {
        return flowNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_vip_savelist.flow_no
     *
     * @param flowNo the value for t_rm_vip_savelist.flow_no
     *
     * @mbggenerated
     */
    public void setFlowNo(String flowNo) {
        this.flowNo = flowNo == null ? null : flowNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_vip_savelist.consum_amt
     *
     * @return the value of t_rm_vip_savelist.consum_amt
     *
     * @mbggenerated
     */
    public BigDecimal getConsumAmt() {
        return consumAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_vip_savelist.consum_amt
     *
     * @param consumAmt the value for t_rm_vip_savelist.consum_amt
     *
     * @mbggenerated
     */
    public void setConsumAmt(BigDecimal consumAmt) {
        this.consumAmt = consumAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_vip_savelist.acc_num
     *
     * @return the value of t_rm_vip_savelist.acc_num
     *
     * @mbggenerated
     */
    public BigDecimal getAccNum() {
        return accNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_vip_savelist.acc_num
     *
     * @param accNum the value for t_rm_vip_savelist.acc_num
     *
     * @mbggenerated
     */
    public void setAccNum(BigDecimal accNum) {
        this.accNum = accNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_vip_savelist.new_cardno
     *
     * @return the value of t_rm_vip_savelist.new_cardno
     *
     * @mbggenerated
     */
    public String getNewCardno() {
        return newCardno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_vip_savelist.new_cardno
     *
     * @param newCardno the value for t_rm_vip_savelist.new_cardno
     *
     * @mbggenerated
     */
    public void setNewCardno(String newCardno) {
        this.newCardno = newCardno == null ? null : newCardno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_vip_savelist.oper_des
     *
     * @return the value of t_rm_vip_savelist.oper_des
     *
     * @mbggenerated
     */
    public String getOperDes() {
        return operDes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_vip_savelist.oper_des
     *
     * @param operDes the value for t_rm_vip_savelist.oper_des
     *
     * @mbggenerated
     */
    public void setOperDes(String operDes) {
        this.operDes = operDes == null ? null : operDes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_vip_savelist.memo
     *
     * @return the value of t_rm_vip_savelist.memo
     *
     * @mbggenerated
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_vip_savelist.memo
     *
     * @param memo the value for t_rm_vip_savelist.memo
     *
     * @mbggenerated
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_vip_savelist.com_flag
     *
     * @return the value of t_rm_vip_savelist.com_flag
     *
     * @mbggenerated
     */
    public String getComFlag() {
        return comFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_vip_savelist.com_flag
     *
     * @param comFlag the value for t_rm_vip_savelist.com_flag
     *
     * @mbggenerated
     */
    public void setComFlag(String comFlag) {
        this.comFlag = comFlag == null ? null : comFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_vip_savelist.sale_qty
     *
     * @return the value of t_rm_vip_savelist.sale_qty
     *
     * @mbggenerated
     */
    public BigDecimal getSaleQty() {
        return saleQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_vip_savelist.sale_qty
     *
     * @param saleQty the value for t_rm_vip_savelist.sale_qty
     *
     * @mbggenerated
     */
    public void setSaleQty(BigDecimal saleQty) {
        this.saleQty = saleQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_vip_savelist.item_no
     *
     * @return the value of t_rm_vip_savelist.item_no
     *
     * @mbggenerated
     */
    public String getItemNo() {
        return itemNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_vip_savelist.item_no
     *
     * @param itemNo the value for t_rm_vip_savelist.item_no
     *
     * @mbggenerated
     */
    public void setItemNo(String itemNo) {
        this.itemNo = itemNo == null ? null : itemNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_vip_savelist.real_amt
     *
     * @return the value of t_rm_vip_savelist.real_amt
     *
     * @mbggenerated
     */
    public BigDecimal getRealAmt() {
        return realAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_vip_savelist.real_amt
     *
     * @param realAmt the value for t_rm_vip_savelist.real_amt
     *
     * @mbggenerated
     */
    public void setRealAmt(BigDecimal realAmt) {
        this.realAmt = realAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_vip_savelist.payway
     *
     * @return the value of t_rm_vip_savelist.payway
     *
     * @mbggenerated
     */
    public String getPayway() {
        return payway;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_vip_savelist.payway
     *
     * @param payway the value for t_rm_vip_savelist.payway
     *
     * @mbggenerated
     */
    public void setPayway(String payway) {
        this.payway = payway == null ? null : payway.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_vip_savelist.other2
     *
     * @return the value of t_rm_vip_savelist.other2
     *
     * @mbggenerated
     */
    public String getOther2() {
        return other2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_vip_savelist.other2
     *
     * @param other2 the value for t_rm_vip_savelist.other2
     *
     * @mbggenerated
     */
    public void setOther2(String other2) {
        this.other2 = other2 == null ? null : other2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_vip_savelist.residue_amt
     *
     * @return the value of t_rm_vip_savelist.residue_amt
     *
     * @mbggenerated
     */
    public BigDecimal getResidueAmt() {
        return residueAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_vip_savelist.residue_amt
     *
     * @param residueAmt the value for t_rm_vip_savelist.residue_amt
     *
     * @mbggenerated
     */
    public void setResidueAmt(BigDecimal residueAmt) {
        this.residueAmt = residueAmt;
    }
}