package com.gd.datachx.entity;

import java.math.BigDecimal;
import java.util.Date;

public class TRmVipInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_vip_info.card_id
     *
     * @mbggenerated
     */
    private String cardId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_vip_info.card_no
     *
     * @mbggenerated
     */
    private String cardNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_vip_info.card_type
     *
     * @mbggenerated
     */
    private String cardType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_vip_info.vip_name
     *
     * @mbggenerated
     */
    private String vipName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_vip_info.vip_sex
     *
     * @mbggenerated
     */
    private String vipSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_vip_info.vip_add
     *
     * @mbggenerated
     */
    private String vipAdd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_vip_info.vip_zip
     *
     * @mbggenerated
     */
    private String vipZip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_vip_info.vip_tel
     *
     * @mbggenerated
     */
    private String vipTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_vip_info.vip_email
     *
     * @mbggenerated
     */
    private String vipEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_vip_info.vip_tax
     *
     * @mbggenerated
     */
    private BigDecimal vipTax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_vip_info.card_status
     *
     * @mbggenerated
     */
    private String cardStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_vip_info.oper_id
     *
     * @mbggenerated
     */
    private String operId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_vip_info.oper_date
     *
     * @mbggenerated
     */
    private Date operDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_vip_info.vip_start_date
     *
     * @mbggenerated
     */
    private Date vipStartDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_vip_info.vip_end_date
     *
     * @mbggenerated
     */
    private Date vipEndDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_vip_info.use_num
     *
     * @mbggenerated
     */
    private Integer useNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_vip_info.birthday
     *
     * @mbggenerated
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_vip_info.social_id
     *
     * @mbggenerated
     */
    private String socialId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_vip_info.save_amt
     *
     * @mbggenerated
     */
    private BigDecimal saveAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_vip_info.residual_amt
     *
     * @mbggenerated
     */
    private String residualAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_vip_info.consum_amt
     *
     * @mbggenerated
     */
    private BigDecimal consumAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_vip_info.consum_count
     *
     * @mbggenerated
     */
    private Integer consumCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_vip_info.company
     *
     * @mbggenerated
     */
    private String company;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_vip_info.duty
     *
     * @mbggenerated
     */
    private String duty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_vip_info.degree
     *
     * @mbggenerated
     */
    private String degree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_vip_info.mobile
     *
     * @mbggenerated
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_vip_info.homeplace
     *
     * @mbggenerated
     */
    private String homeplace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_vip_info.reg_place
     *
     * @mbggenerated
     */
    private String regPlace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_vip_info.live_place
     *
     * @mbggenerated
     */
    private String livePlace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_vip_info.marriage
     *
     * @mbggenerated
     */
    private String marriage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_vip_info.salary_level
     *
     * @mbggenerated
     */
    private String salaryLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_vip_info.nation
     *
     * @mbggenerated
     */
    private String nation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_vip_info.height
     *
     * @mbggenerated
     */
    private Short height;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_vip_info.weight
     *
     * @mbggenerated
     */
    private BigDecimal weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_vip_info.blood_type
     *
     * @mbggenerated
     */
    private String bloodType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_vip_info.favor
     *
     * @mbggenerated
     */
    private String favor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_vip_info.now_acc_num
     *
     * @mbggenerated
     */
    private BigDecimal nowAccNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_vip_info.acc_num
     *
     * @mbggenerated
     */
    private BigDecimal accNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_vip_info.dec_num
     *
     * @mbggenerated
     */
    private BigDecimal decNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_vip_info.pass
     *
     * @mbggenerated
     */
    private String pass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_vip_info.modify_date
     *
     * @mbggenerated
     */
    private Date modifyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_vip_info.com_flag
     *
     * @mbggenerated
     */
    private String comFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_vip_info.photo
     *
     * @mbggenerated
     */
    private String photo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_vip_info.memo
     *
     * @mbggenerated
     */
    private String memo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_vip_info.father_card
     *
     * @mbggenerated
     */
    private String fatherCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_vip_info.item_amt
     *
     * @mbggenerated
     */
    private BigDecimal itemAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_vip_info.branch_no
     *
     * @mbggenerated
     */
    private String branchNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_vip_info.sav_start_date
     *
     * @mbggenerated
     */
    private Date savStartDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_vip_info.sav_end_date
     *
     * @mbggenerated
     */
    private Date savEndDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_vip_info.source_card_id
     *
     * @mbggenerated
     */
    private String sourceCardId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_vip_info.vip_add1
     *
     * @mbggenerated
     */
    private String vipAdd1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_vip_info.vip_add2
     *
     * @mbggenerated
     */
    private String vipAdd2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_vip_info.annex_property1
     *
     * @mbggenerated
     */
    private String annexProperty1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_vip_info.annex_property2
     *
     * @mbggenerated
     */
    private String annexProperty2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_vip_info.annex_property3
     *
     * @mbggenerated
     */
    private String annexProperty3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_vip_info.annex_property4
     *
     * @mbggenerated
     */
    private String annexProperty4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_vip_info.annex_property5
     *
     * @mbggenerated
     */
    private String annexProperty5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_vip_info.annex_property6
     *
     * @mbggenerated
     */
    private String annexProperty6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_vip_info.annex_property7
     *
     * @mbggenerated
     */
    private String annexProperty7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_vip_info.annex_property8
     *
     * @mbggenerated
     */
    private String annexProperty8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_vip_info.annex_property9
     *
     * @mbggenerated
     */
    private String annexProperty9;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_vip_info.annex_property10
     *
     * @mbggenerated
     */
    private String annexProperty10;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_vip_info.picture_type
     *
     * @mbggenerated
     */
    private String pictureType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_vip_info.vip_spec_date1
     *
     * @mbggenerated
     */
    private Date vipSpecDate1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_vip_info.vip_spec_date2
     *
     * @mbggenerated
     */
    private Date vipSpecDate2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_vip_info.vip_spec_date3
     *
     * @mbggenerated
     */
    private Date vipSpecDate3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_vip_info.bth_flag
     *
     * @mbggenerated
     */
    private String bthFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_vip_info.vip_credentials
     *
     * @mbggenerated
     */
    private String vipCredentials;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_vip_info.vip_work
     *
     * @mbggenerated
     */
    private String vipWork;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_vip_info.vip_intent
     *
     * @mbggenerated
     */
    private String vipIntent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_vip_info.pur_hobbies
     *
     * @mbggenerated
     */
    private String purHobbies;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_vip_info.characteristics
     *
     * @mbggenerated
     */
    private String characteristics;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_vip_info.vip_trade
     *
     * @mbggenerated
     */
    private String vipTrade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_vip_info.vip_rem
     *
     * @mbggenerated
     */
    private String vipRem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_vip_info.oper_id_make
     *
     * @mbggenerated
     */
    private String operIdMake;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_vip_info.oper_date_make
     *
     * @mbggenerated
     */
    private Date operDateMake;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_vip_info.oper_date_gi
     *
     * @mbggenerated
     */
    private Date operDateGi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_vip_info.oper_id_gi
     *
     * @mbggenerated
     */
    private String operIdGi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_vip_info.is_makecard
     *
     * @mbggenerated
     */
    private String isMakecard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_vip_info.IsAlive
     *
     * @mbggenerated
     */
    private String isalive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_vip_info.send_amt
     *
     * @mbggenerated
     */
    private BigDecimal sendAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_vip_info.send_start_date
     *
     * @mbggenerated
     */
    private Date sendStartDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rm_vip_info.send_end_date
     *
     * @mbggenerated
     */
    private Date sendEndDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_vip_info.card_id
     *
     * @return the value of t_rm_vip_info.card_id
     *
     * @mbggenerated
     */
    public String getCardId() {
        return cardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_vip_info.card_id
     *
     * @param cardId the value for t_rm_vip_info.card_id
     *
     * @mbggenerated
     */
    public void setCardId(String cardId) {
        this.cardId = cardId == null ? null : cardId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_vip_info.card_no
     *
     * @return the value of t_rm_vip_info.card_no
     *
     * @mbggenerated
     */
    public String getCardNo() {
        return cardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_vip_info.card_no
     *
     * @param cardNo the value for t_rm_vip_info.card_no
     *
     * @mbggenerated
     */
    public void setCardNo(String cardNo) {
        this.cardNo = cardNo == null ? null : cardNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_vip_info.card_type
     *
     * @return the value of t_rm_vip_info.card_type
     *
     * @mbggenerated
     */
    public String getCardType() {
        return cardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_vip_info.card_type
     *
     * @param cardType the value for t_rm_vip_info.card_type
     *
     * @mbggenerated
     */
    public void setCardType(String cardType) {
        this.cardType = cardType == null ? null : cardType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_vip_info.vip_name
     *
     * @return the value of t_rm_vip_info.vip_name
     *
     * @mbggenerated
     */
    public String getVipName() {
        return vipName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_vip_info.vip_name
     *
     * @param vipName the value for t_rm_vip_info.vip_name
     *
     * @mbggenerated
     */
    public void setVipName(String vipName) {
        this.vipName = vipName == null ? null : vipName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_vip_info.vip_sex
     *
     * @return the value of t_rm_vip_info.vip_sex
     *
     * @mbggenerated
     */
    public String getVipSex() {
        return vipSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_vip_info.vip_sex
     *
     * @param vipSex the value for t_rm_vip_info.vip_sex
     *
     * @mbggenerated
     */
    public void setVipSex(String vipSex) {
        this.vipSex = vipSex == null ? null : vipSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_vip_info.vip_add
     *
     * @return the value of t_rm_vip_info.vip_add
     *
     * @mbggenerated
     */
    public String getVipAdd() {
        return vipAdd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_vip_info.vip_add
     *
     * @param vipAdd the value for t_rm_vip_info.vip_add
     *
     * @mbggenerated
     */
    public void setVipAdd(String vipAdd) {
        this.vipAdd = vipAdd == null ? null : vipAdd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_vip_info.vip_zip
     *
     * @return the value of t_rm_vip_info.vip_zip
     *
     * @mbggenerated
     */
    public String getVipZip() {
        return vipZip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_vip_info.vip_zip
     *
     * @param vipZip the value for t_rm_vip_info.vip_zip
     *
     * @mbggenerated
     */
    public void setVipZip(String vipZip) {
        this.vipZip = vipZip == null ? null : vipZip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_vip_info.vip_tel
     *
     * @return the value of t_rm_vip_info.vip_tel
     *
     * @mbggenerated
     */
    public String getVipTel() {
        return vipTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_vip_info.vip_tel
     *
     * @param vipTel the value for t_rm_vip_info.vip_tel
     *
     * @mbggenerated
     */
    public void setVipTel(String vipTel) {
        this.vipTel = vipTel == null ? null : vipTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_vip_info.vip_email
     *
     * @return the value of t_rm_vip_info.vip_email
     *
     * @mbggenerated
     */
    public String getVipEmail() {
        return vipEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_vip_info.vip_email
     *
     * @param vipEmail the value for t_rm_vip_info.vip_email
     *
     * @mbggenerated
     */
    public void setVipEmail(String vipEmail) {
        this.vipEmail = vipEmail == null ? null : vipEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_vip_info.vip_tax
     *
     * @return the value of t_rm_vip_info.vip_tax
     *
     * @mbggenerated
     */
    public BigDecimal getVipTax() {
        return vipTax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_vip_info.vip_tax
     *
     * @param vipTax the value for t_rm_vip_info.vip_tax
     *
     * @mbggenerated
     */
    public void setVipTax(BigDecimal vipTax) {
        this.vipTax = vipTax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_vip_info.card_status
     *
     * @return the value of t_rm_vip_info.card_status
     *
     * @mbggenerated
     */
    public String getCardStatus() {
        return cardStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_vip_info.card_status
     *
     * @param cardStatus the value for t_rm_vip_info.card_status
     *
     * @mbggenerated
     */
    public void setCardStatus(String cardStatus) {
        this.cardStatus = cardStatus == null ? null : cardStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_vip_info.oper_id
     *
     * @return the value of t_rm_vip_info.oper_id
     *
     * @mbggenerated
     */
    public String getOperId() {
        return operId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_vip_info.oper_id
     *
     * @param operId the value for t_rm_vip_info.oper_id
     *
     * @mbggenerated
     */
    public void setOperId(String operId) {
        this.operId = operId == null ? null : operId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_vip_info.oper_date
     *
     * @return the value of t_rm_vip_info.oper_date
     *
     * @mbggenerated
     */
    public Date getOperDate() {
        return operDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_vip_info.oper_date
     *
     * @param operDate the value for t_rm_vip_info.oper_date
     *
     * @mbggenerated
     */
    public void setOperDate(Date operDate) {
        this.operDate = operDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_vip_info.vip_start_date
     *
     * @return the value of t_rm_vip_info.vip_start_date
     *
     * @mbggenerated
     */
    public Date getVipStartDate() {
        return vipStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_vip_info.vip_start_date
     *
     * @param vipStartDate the value for t_rm_vip_info.vip_start_date
     *
     * @mbggenerated
     */
    public void setVipStartDate(Date vipStartDate) {
        this.vipStartDate = vipStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_vip_info.vip_end_date
     *
     * @return the value of t_rm_vip_info.vip_end_date
     *
     * @mbggenerated
     */
    public Date getVipEndDate() {
        return vipEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_vip_info.vip_end_date
     *
     * @param vipEndDate the value for t_rm_vip_info.vip_end_date
     *
     * @mbggenerated
     */
    public void setVipEndDate(Date vipEndDate) {
        this.vipEndDate = vipEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_vip_info.use_num
     *
     * @return the value of t_rm_vip_info.use_num
     *
     * @mbggenerated
     */
    public Integer getUseNum() {
        return useNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_vip_info.use_num
     *
     * @param useNum the value for t_rm_vip_info.use_num
     *
     * @mbggenerated
     */
    public void setUseNum(Integer useNum) {
        this.useNum = useNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_vip_info.birthday
     *
     * @return the value of t_rm_vip_info.birthday
     *
     * @mbggenerated
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_vip_info.birthday
     *
     * @param birthday the value for t_rm_vip_info.birthday
     *
     * @mbggenerated
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_vip_info.social_id
     *
     * @return the value of t_rm_vip_info.social_id
     *
     * @mbggenerated
     */
    public String getSocialId() {
        return socialId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_vip_info.social_id
     *
     * @param socialId the value for t_rm_vip_info.social_id
     *
     * @mbggenerated
     */
    public void setSocialId(String socialId) {
        this.socialId = socialId == null ? null : socialId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_vip_info.save_amt
     *
     * @return the value of t_rm_vip_info.save_amt
     *
     * @mbggenerated
     */
    public BigDecimal getSaveAmt() {
        return saveAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_vip_info.save_amt
     *
     * @param saveAmt the value for t_rm_vip_info.save_amt
     *
     * @mbggenerated
     */
    public void setSaveAmt(BigDecimal saveAmt) {
        this.saveAmt = saveAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_vip_info.residual_amt
     *
     * @return the value of t_rm_vip_info.residual_amt
     *
     * @mbggenerated
     */
    public String getResidualAmt() {
        return residualAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_vip_info.residual_amt
     *
     * @param residualAmt the value for t_rm_vip_info.residual_amt
     *
     * @mbggenerated
     */
    public void setResidualAmt(String residualAmt) {
        this.residualAmt = residualAmt == null ? null : residualAmt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_vip_info.consum_amt
     *
     * @return the value of t_rm_vip_info.consum_amt
     *
     * @mbggenerated
     */
    public BigDecimal getConsumAmt() {
        return consumAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_vip_info.consum_amt
     *
     * @param consumAmt the value for t_rm_vip_info.consum_amt
     *
     * @mbggenerated
     */
    public void setConsumAmt(BigDecimal consumAmt) {
        this.consumAmt = consumAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_vip_info.consum_count
     *
     * @return the value of t_rm_vip_info.consum_count
     *
     * @mbggenerated
     */
    public Integer getConsumCount() {
        return consumCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_vip_info.consum_count
     *
     * @param consumCount the value for t_rm_vip_info.consum_count
     *
     * @mbggenerated
     */
    public void setConsumCount(Integer consumCount) {
        this.consumCount = consumCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_vip_info.company
     *
     * @return the value of t_rm_vip_info.company
     *
     * @mbggenerated
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_vip_info.company
     *
     * @param company the value for t_rm_vip_info.company
     *
     * @mbggenerated
     */
    public void setCompany(String company) {
        this.company = company == null ? null : company.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_vip_info.duty
     *
     * @return the value of t_rm_vip_info.duty
     *
     * @mbggenerated
     */
    public String getDuty() {
        return duty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_vip_info.duty
     *
     * @param duty the value for t_rm_vip_info.duty
     *
     * @mbggenerated
     */
    public void setDuty(String duty) {
        this.duty = duty == null ? null : duty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_vip_info.degree
     *
     * @return the value of t_rm_vip_info.degree
     *
     * @mbggenerated
     */
    public String getDegree() {
        return degree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_vip_info.degree
     *
     * @param degree the value for t_rm_vip_info.degree
     *
     * @mbggenerated
     */
    public void setDegree(String degree) {
        this.degree = degree == null ? null : degree.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_vip_info.mobile
     *
     * @return the value of t_rm_vip_info.mobile
     *
     * @mbggenerated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_vip_info.mobile
     *
     * @param mobile the value for t_rm_vip_info.mobile
     *
     * @mbggenerated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_vip_info.homeplace
     *
     * @return the value of t_rm_vip_info.homeplace
     *
     * @mbggenerated
     */
    public String getHomeplace() {
        return homeplace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_vip_info.homeplace
     *
     * @param homeplace the value for t_rm_vip_info.homeplace
     *
     * @mbggenerated
     */
    public void setHomeplace(String homeplace) {
        this.homeplace = homeplace == null ? null : homeplace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_vip_info.reg_place
     *
     * @return the value of t_rm_vip_info.reg_place
     *
     * @mbggenerated
     */
    public String getRegPlace() {
        return regPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_vip_info.reg_place
     *
     * @param regPlace the value for t_rm_vip_info.reg_place
     *
     * @mbggenerated
     */
    public void setRegPlace(String regPlace) {
        this.regPlace = regPlace == null ? null : regPlace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_vip_info.live_place
     *
     * @return the value of t_rm_vip_info.live_place
     *
     * @mbggenerated
     */
    public String getLivePlace() {
        return livePlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_vip_info.live_place
     *
     * @param livePlace the value for t_rm_vip_info.live_place
     *
     * @mbggenerated
     */
    public void setLivePlace(String livePlace) {
        this.livePlace = livePlace == null ? null : livePlace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_vip_info.marriage
     *
     * @return the value of t_rm_vip_info.marriage
     *
     * @mbggenerated
     */
    public String getMarriage() {
        return marriage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_vip_info.marriage
     *
     * @param marriage the value for t_rm_vip_info.marriage
     *
     * @mbggenerated
     */
    public void setMarriage(String marriage) {
        this.marriage = marriage == null ? null : marriage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_vip_info.salary_level
     *
     * @return the value of t_rm_vip_info.salary_level
     *
     * @mbggenerated
     */
    public String getSalaryLevel() {
        return salaryLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_vip_info.salary_level
     *
     * @param salaryLevel the value for t_rm_vip_info.salary_level
     *
     * @mbggenerated
     */
    public void setSalaryLevel(String salaryLevel) {
        this.salaryLevel = salaryLevel == null ? null : salaryLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_vip_info.nation
     *
     * @return the value of t_rm_vip_info.nation
     *
     * @mbggenerated
     */
    public String getNation() {
        return nation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_vip_info.nation
     *
     * @param nation the value for t_rm_vip_info.nation
     *
     * @mbggenerated
     */
    public void setNation(String nation) {
        this.nation = nation == null ? null : nation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_vip_info.height
     *
     * @return the value of t_rm_vip_info.height
     *
     * @mbggenerated
     */
    public Short getHeight() {
        return height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_vip_info.height
     *
     * @param height the value for t_rm_vip_info.height
     *
     * @mbggenerated
     */
    public void setHeight(Short height) {
        this.height = height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_vip_info.weight
     *
     * @return the value of t_rm_vip_info.weight
     *
     * @mbggenerated
     */
    public BigDecimal getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_vip_info.weight
     *
     * @param weight the value for t_rm_vip_info.weight
     *
     * @mbggenerated
     */
    public void setWeight(BigDecimal weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_vip_info.blood_type
     *
     * @return the value of t_rm_vip_info.blood_type
     *
     * @mbggenerated
     */
    public String getBloodType() {
        return bloodType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_vip_info.blood_type
     *
     * @param bloodType the value for t_rm_vip_info.blood_type
     *
     * @mbggenerated
     */
    public void setBloodType(String bloodType) {
        this.bloodType = bloodType == null ? null : bloodType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_vip_info.favor
     *
     * @return the value of t_rm_vip_info.favor
     *
     * @mbggenerated
     */
    public String getFavor() {
        return favor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_vip_info.favor
     *
     * @param favor the value for t_rm_vip_info.favor
     *
     * @mbggenerated
     */
    public void setFavor(String favor) {
        this.favor = favor == null ? null : favor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_vip_info.now_acc_num
     *
     * @return the value of t_rm_vip_info.now_acc_num
     *
     * @mbggenerated
     */
    public BigDecimal getNowAccNum() {
        return nowAccNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_vip_info.now_acc_num
     *
     * @param nowAccNum the value for t_rm_vip_info.now_acc_num
     *
     * @mbggenerated
     */
    public void setNowAccNum(BigDecimal nowAccNum) {
        this.nowAccNum = nowAccNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_vip_info.acc_num
     *
     * @return the value of t_rm_vip_info.acc_num
     *
     * @mbggenerated
     */
    public BigDecimal getAccNum() {
        return accNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_vip_info.acc_num
     *
     * @param accNum the value for t_rm_vip_info.acc_num
     *
     * @mbggenerated
     */
    public void setAccNum(BigDecimal accNum) {
        this.accNum = accNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_vip_info.dec_num
     *
     * @return the value of t_rm_vip_info.dec_num
     *
     * @mbggenerated
     */
    public BigDecimal getDecNum() {
        return decNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_vip_info.dec_num
     *
     * @param decNum the value for t_rm_vip_info.dec_num
     *
     * @mbggenerated
     */
    public void setDecNum(BigDecimal decNum) {
        this.decNum = decNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_vip_info.pass
     *
     * @return the value of t_rm_vip_info.pass
     *
     * @mbggenerated
     */
    public String getPass() {
        return pass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_vip_info.pass
     *
     * @param pass the value for t_rm_vip_info.pass
     *
     * @mbggenerated
     */
    public void setPass(String pass) {
        this.pass = pass == null ? null : pass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_vip_info.modify_date
     *
     * @return the value of t_rm_vip_info.modify_date
     *
     * @mbggenerated
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_vip_info.modify_date
     *
     * @param modifyDate the value for t_rm_vip_info.modify_date
     *
     * @mbggenerated
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_vip_info.com_flag
     *
     * @return the value of t_rm_vip_info.com_flag
     *
     * @mbggenerated
     */
    public String getComFlag() {
        return comFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_vip_info.com_flag
     *
     * @param comFlag the value for t_rm_vip_info.com_flag
     *
     * @mbggenerated
     */
    public void setComFlag(String comFlag) {
        this.comFlag = comFlag == null ? null : comFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_vip_info.photo
     *
     * @return the value of t_rm_vip_info.photo
     *
     * @mbggenerated
     */
    public String getPhoto() {
        return photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_vip_info.photo
     *
     * @param photo the value for t_rm_vip_info.photo
     *
     * @mbggenerated
     */
    public void setPhoto(String photo) {
        this.photo = photo == null ? null : photo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_vip_info.memo
     *
     * @return the value of t_rm_vip_info.memo
     *
     * @mbggenerated
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_vip_info.memo
     *
     * @param memo the value for t_rm_vip_info.memo
     *
     * @mbggenerated
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_vip_info.father_card
     *
     * @return the value of t_rm_vip_info.father_card
     *
     * @mbggenerated
     */
    public String getFatherCard() {
        return fatherCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_vip_info.father_card
     *
     * @param fatherCard the value for t_rm_vip_info.father_card
     *
     * @mbggenerated
     */
    public void setFatherCard(String fatherCard) {
        this.fatherCard = fatherCard == null ? null : fatherCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_vip_info.item_amt
     *
     * @return the value of t_rm_vip_info.item_amt
     *
     * @mbggenerated
     */
    public BigDecimal getItemAmt() {
        return itemAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_vip_info.item_amt
     *
     * @param itemAmt the value for t_rm_vip_info.item_amt
     *
     * @mbggenerated
     */
    public void setItemAmt(BigDecimal itemAmt) {
        this.itemAmt = itemAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_vip_info.branch_no
     *
     * @return the value of t_rm_vip_info.branch_no
     *
     * @mbggenerated
     */
    public String getBranchNo() {
        return branchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_vip_info.branch_no
     *
     * @param branchNo the value for t_rm_vip_info.branch_no
     *
     * @mbggenerated
     */
    public void setBranchNo(String branchNo) {
        this.branchNo = branchNo == null ? null : branchNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_vip_info.sav_start_date
     *
     * @return the value of t_rm_vip_info.sav_start_date
     *
     * @mbggenerated
     */
    public Date getSavStartDate() {
        return savStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_vip_info.sav_start_date
     *
     * @param savStartDate the value for t_rm_vip_info.sav_start_date
     *
     * @mbggenerated
     */
    public void setSavStartDate(Date savStartDate) {
        this.savStartDate = savStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_vip_info.sav_end_date
     *
     * @return the value of t_rm_vip_info.sav_end_date
     *
     * @mbggenerated
     */
    public Date getSavEndDate() {
        return savEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_vip_info.sav_end_date
     *
     * @param savEndDate the value for t_rm_vip_info.sav_end_date
     *
     * @mbggenerated
     */
    public void setSavEndDate(Date savEndDate) {
        this.savEndDate = savEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_vip_info.source_card_id
     *
     * @return the value of t_rm_vip_info.source_card_id
     *
     * @mbggenerated
     */
    public String getSourceCardId() {
        return sourceCardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_vip_info.source_card_id
     *
     * @param sourceCardId the value for t_rm_vip_info.source_card_id
     *
     * @mbggenerated
     */
    public void setSourceCardId(String sourceCardId) {
        this.sourceCardId = sourceCardId == null ? null : sourceCardId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_vip_info.vip_add1
     *
     * @return the value of t_rm_vip_info.vip_add1
     *
     * @mbggenerated
     */
    public String getVipAdd1() {
        return vipAdd1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_vip_info.vip_add1
     *
     * @param vipAdd1 the value for t_rm_vip_info.vip_add1
     *
     * @mbggenerated
     */
    public void setVipAdd1(String vipAdd1) {
        this.vipAdd1 = vipAdd1 == null ? null : vipAdd1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_vip_info.vip_add2
     *
     * @return the value of t_rm_vip_info.vip_add2
     *
     * @mbggenerated
     */
    public String getVipAdd2() {
        return vipAdd2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_vip_info.vip_add2
     *
     * @param vipAdd2 the value for t_rm_vip_info.vip_add2
     *
     * @mbggenerated
     */
    public void setVipAdd2(String vipAdd2) {
        this.vipAdd2 = vipAdd2 == null ? null : vipAdd2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_vip_info.annex_property1
     *
     * @return the value of t_rm_vip_info.annex_property1
     *
     * @mbggenerated
     */
    public String getAnnexProperty1() {
        return annexProperty1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_vip_info.annex_property1
     *
     * @param annexProperty1 the value for t_rm_vip_info.annex_property1
     *
     * @mbggenerated
     */
    public void setAnnexProperty1(String annexProperty1) {
        this.annexProperty1 = annexProperty1 == null ? null : annexProperty1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_vip_info.annex_property2
     *
     * @return the value of t_rm_vip_info.annex_property2
     *
     * @mbggenerated
     */
    public String getAnnexProperty2() {
        return annexProperty2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_vip_info.annex_property2
     *
     * @param annexProperty2 the value for t_rm_vip_info.annex_property2
     *
     * @mbggenerated
     */
    public void setAnnexProperty2(String annexProperty2) {
        this.annexProperty2 = annexProperty2 == null ? null : annexProperty2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_vip_info.annex_property3
     *
     * @return the value of t_rm_vip_info.annex_property3
     *
     * @mbggenerated
     */
    public String getAnnexProperty3() {
        return annexProperty3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_vip_info.annex_property3
     *
     * @param annexProperty3 the value for t_rm_vip_info.annex_property3
     *
     * @mbggenerated
     */
    public void setAnnexProperty3(String annexProperty3) {
        this.annexProperty3 = annexProperty3 == null ? null : annexProperty3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_vip_info.annex_property4
     *
     * @return the value of t_rm_vip_info.annex_property4
     *
     * @mbggenerated
     */
    public String getAnnexProperty4() {
        return annexProperty4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_vip_info.annex_property4
     *
     * @param annexProperty4 the value for t_rm_vip_info.annex_property4
     *
     * @mbggenerated
     */
    public void setAnnexProperty4(String annexProperty4) {
        this.annexProperty4 = annexProperty4 == null ? null : annexProperty4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_vip_info.annex_property5
     *
     * @return the value of t_rm_vip_info.annex_property5
     *
     * @mbggenerated
     */
    public String getAnnexProperty5() {
        return annexProperty5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_vip_info.annex_property5
     *
     * @param annexProperty5 the value for t_rm_vip_info.annex_property5
     *
     * @mbggenerated
     */
    public void setAnnexProperty5(String annexProperty5) {
        this.annexProperty5 = annexProperty5 == null ? null : annexProperty5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_vip_info.annex_property6
     *
     * @return the value of t_rm_vip_info.annex_property6
     *
     * @mbggenerated
     */
    public String getAnnexProperty6() {
        return annexProperty6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_vip_info.annex_property6
     *
     * @param annexProperty6 the value for t_rm_vip_info.annex_property6
     *
     * @mbggenerated
     */
    public void setAnnexProperty6(String annexProperty6) {
        this.annexProperty6 = annexProperty6 == null ? null : annexProperty6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_vip_info.annex_property7
     *
     * @return the value of t_rm_vip_info.annex_property7
     *
     * @mbggenerated
     */
    public String getAnnexProperty7() {
        return annexProperty7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_vip_info.annex_property7
     *
     * @param annexProperty7 the value for t_rm_vip_info.annex_property7
     *
     * @mbggenerated
     */
    public void setAnnexProperty7(String annexProperty7) {
        this.annexProperty7 = annexProperty7 == null ? null : annexProperty7.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_vip_info.annex_property8
     *
     * @return the value of t_rm_vip_info.annex_property8
     *
     * @mbggenerated
     */
    public String getAnnexProperty8() {
        return annexProperty8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_vip_info.annex_property8
     *
     * @param annexProperty8 the value for t_rm_vip_info.annex_property8
     *
     * @mbggenerated
     */
    public void setAnnexProperty8(String annexProperty8) {
        this.annexProperty8 = annexProperty8 == null ? null : annexProperty8.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_vip_info.annex_property9
     *
     * @return the value of t_rm_vip_info.annex_property9
     *
     * @mbggenerated
     */
    public String getAnnexProperty9() {
        return annexProperty9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_vip_info.annex_property9
     *
     * @param annexProperty9 the value for t_rm_vip_info.annex_property9
     *
     * @mbggenerated
     */
    public void setAnnexProperty9(String annexProperty9) {
        this.annexProperty9 = annexProperty9 == null ? null : annexProperty9.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_vip_info.annex_property10
     *
     * @return the value of t_rm_vip_info.annex_property10
     *
     * @mbggenerated
     */
    public String getAnnexProperty10() {
        return annexProperty10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_vip_info.annex_property10
     *
     * @param annexProperty10 the value for t_rm_vip_info.annex_property10
     *
     * @mbggenerated
     */
    public void setAnnexProperty10(String annexProperty10) {
        this.annexProperty10 = annexProperty10 == null ? null : annexProperty10.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_vip_info.picture_type
     *
     * @return the value of t_rm_vip_info.picture_type
     *
     * @mbggenerated
     */
    public String getPictureType() {
        return pictureType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_vip_info.picture_type
     *
     * @param pictureType the value for t_rm_vip_info.picture_type
     *
     * @mbggenerated
     */
    public void setPictureType(String pictureType) {
        this.pictureType = pictureType == null ? null : pictureType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_vip_info.vip_spec_date1
     *
     * @return the value of t_rm_vip_info.vip_spec_date1
     *
     * @mbggenerated
     */
    public Date getVipSpecDate1() {
        return vipSpecDate1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_vip_info.vip_spec_date1
     *
     * @param vipSpecDate1 the value for t_rm_vip_info.vip_spec_date1
     *
     * @mbggenerated
     */
    public void setVipSpecDate1(Date vipSpecDate1) {
        this.vipSpecDate1 = vipSpecDate1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_vip_info.vip_spec_date2
     *
     * @return the value of t_rm_vip_info.vip_spec_date2
     *
     * @mbggenerated
     */
    public Date getVipSpecDate2() {
        return vipSpecDate2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_vip_info.vip_spec_date2
     *
     * @param vipSpecDate2 the value for t_rm_vip_info.vip_spec_date2
     *
     * @mbggenerated
     */
    public void setVipSpecDate2(Date vipSpecDate2) {
        this.vipSpecDate2 = vipSpecDate2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_vip_info.vip_spec_date3
     *
     * @return the value of t_rm_vip_info.vip_spec_date3
     *
     * @mbggenerated
     */
    public Date getVipSpecDate3() {
        return vipSpecDate3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_vip_info.vip_spec_date3
     *
     * @param vipSpecDate3 the value for t_rm_vip_info.vip_spec_date3
     *
     * @mbggenerated
     */
    public void setVipSpecDate3(Date vipSpecDate3) {
        this.vipSpecDate3 = vipSpecDate3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_vip_info.bth_flag
     *
     * @return the value of t_rm_vip_info.bth_flag
     *
     * @mbggenerated
     */
    public String getBthFlag() {
        return bthFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_vip_info.bth_flag
     *
     * @param bthFlag the value for t_rm_vip_info.bth_flag
     *
     * @mbggenerated
     */
    public void setBthFlag(String bthFlag) {
        this.bthFlag = bthFlag == null ? null : bthFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_vip_info.vip_credentials
     *
     * @return the value of t_rm_vip_info.vip_credentials
     *
     * @mbggenerated
     */
    public String getVipCredentials() {
        return vipCredentials;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_vip_info.vip_credentials
     *
     * @param vipCredentials the value for t_rm_vip_info.vip_credentials
     *
     * @mbggenerated
     */
    public void setVipCredentials(String vipCredentials) {
        this.vipCredentials = vipCredentials == null ? null : vipCredentials.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_vip_info.vip_work
     *
     * @return the value of t_rm_vip_info.vip_work
     *
     * @mbggenerated
     */
    public String getVipWork() {
        return vipWork;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_vip_info.vip_work
     *
     * @param vipWork the value for t_rm_vip_info.vip_work
     *
     * @mbggenerated
     */
    public void setVipWork(String vipWork) {
        this.vipWork = vipWork == null ? null : vipWork.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_vip_info.vip_intent
     *
     * @return the value of t_rm_vip_info.vip_intent
     *
     * @mbggenerated
     */
    public String getVipIntent() {
        return vipIntent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_vip_info.vip_intent
     *
     * @param vipIntent the value for t_rm_vip_info.vip_intent
     *
     * @mbggenerated
     */
    public void setVipIntent(String vipIntent) {
        this.vipIntent = vipIntent == null ? null : vipIntent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_vip_info.pur_hobbies
     *
     * @return the value of t_rm_vip_info.pur_hobbies
     *
     * @mbggenerated
     */
    public String getPurHobbies() {
        return purHobbies;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_vip_info.pur_hobbies
     *
     * @param purHobbies the value for t_rm_vip_info.pur_hobbies
     *
     * @mbggenerated
     */
    public void setPurHobbies(String purHobbies) {
        this.purHobbies = purHobbies == null ? null : purHobbies.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_vip_info.characteristics
     *
     * @return the value of t_rm_vip_info.characteristics
     *
     * @mbggenerated
     */
    public String getCharacteristics() {
        return characteristics;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_vip_info.characteristics
     *
     * @param characteristics the value for t_rm_vip_info.characteristics
     *
     * @mbggenerated
     */
    public void setCharacteristics(String characteristics) {
        this.characteristics = characteristics == null ? null : characteristics.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_vip_info.vip_trade
     *
     * @return the value of t_rm_vip_info.vip_trade
     *
     * @mbggenerated
     */
    public String getVipTrade() {
        return vipTrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_vip_info.vip_trade
     *
     * @param vipTrade the value for t_rm_vip_info.vip_trade
     *
     * @mbggenerated
     */
    public void setVipTrade(String vipTrade) {
        this.vipTrade = vipTrade == null ? null : vipTrade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_vip_info.vip_rem
     *
     * @return the value of t_rm_vip_info.vip_rem
     *
     * @mbggenerated
     */
    public String getVipRem() {
        return vipRem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_vip_info.vip_rem
     *
     * @param vipRem the value for t_rm_vip_info.vip_rem
     *
     * @mbggenerated
     */
    public void setVipRem(String vipRem) {
        this.vipRem = vipRem == null ? null : vipRem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_vip_info.oper_id_make
     *
     * @return the value of t_rm_vip_info.oper_id_make
     *
     * @mbggenerated
     */
    public String getOperIdMake() {
        return operIdMake;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_vip_info.oper_id_make
     *
     * @param operIdMake the value for t_rm_vip_info.oper_id_make
     *
     * @mbggenerated
     */
    public void setOperIdMake(String operIdMake) {
        this.operIdMake = operIdMake == null ? null : operIdMake.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_vip_info.oper_date_make
     *
     * @return the value of t_rm_vip_info.oper_date_make
     *
     * @mbggenerated
     */
    public Date getOperDateMake() {
        return operDateMake;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_vip_info.oper_date_make
     *
     * @param operDateMake the value for t_rm_vip_info.oper_date_make
     *
     * @mbggenerated
     */
    public void setOperDateMake(Date operDateMake) {
        this.operDateMake = operDateMake;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_vip_info.oper_date_gi
     *
     * @return the value of t_rm_vip_info.oper_date_gi
     *
     * @mbggenerated
     */
    public Date getOperDateGi() {
        return operDateGi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_vip_info.oper_date_gi
     *
     * @param operDateGi the value for t_rm_vip_info.oper_date_gi
     *
     * @mbggenerated
     */
    public void setOperDateGi(Date operDateGi) {
        this.operDateGi = operDateGi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_vip_info.oper_id_gi
     *
     * @return the value of t_rm_vip_info.oper_id_gi
     *
     * @mbggenerated
     */
    public String getOperIdGi() {
        return operIdGi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_vip_info.oper_id_gi
     *
     * @param operIdGi the value for t_rm_vip_info.oper_id_gi
     *
     * @mbggenerated
     */
    public void setOperIdGi(String operIdGi) {
        this.operIdGi = operIdGi == null ? null : operIdGi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_vip_info.is_makecard
     *
     * @return the value of t_rm_vip_info.is_makecard
     *
     * @mbggenerated
     */
    public String getIsMakecard() {
        return isMakecard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_vip_info.is_makecard
     *
     * @param isMakecard the value for t_rm_vip_info.is_makecard
     *
     * @mbggenerated
     */
    public void setIsMakecard(String isMakecard) {
        this.isMakecard = isMakecard == null ? null : isMakecard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_vip_info.IsAlive
     *
     * @return the value of t_rm_vip_info.IsAlive
     *
     * @mbggenerated
     */
    public String getIsalive() {
        return isalive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_vip_info.IsAlive
     *
     * @param isalive the value for t_rm_vip_info.IsAlive
     *
     * @mbggenerated
     */
    public void setIsalive(String isalive) {
        this.isalive = isalive == null ? null : isalive.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_vip_info.send_amt
     *
     * @return the value of t_rm_vip_info.send_amt
     *
     * @mbggenerated
     */
    public BigDecimal getSendAmt() {
        return sendAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_vip_info.send_amt
     *
     * @param sendAmt the value for t_rm_vip_info.send_amt
     *
     * @mbggenerated
     */
    public void setSendAmt(BigDecimal sendAmt) {
        this.sendAmt = sendAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_vip_info.send_start_date
     *
     * @return the value of t_rm_vip_info.send_start_date
     *
     * @mbggenerated
     */
    public Date getSendStartDate() {
        return sendStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_vip_info.send_start_date
     *
     * @param sendStartDate the value for t_rm_vip_info.send_start_date
     *
     * @mbggenerated
     */
    public void setSendStartDate(Date sendStartDate) {
        this.sendStartDate = sendStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rm_vip_info.send_end_date
     *
     * @return the value of t_rm_vip_info.send_end_date
     *
     * @mbggenerated
     */
    public Date getSendEndDate() {
        return sendEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rm_vip_info.send_end_date
     *
     * @param sendEndDate the value for t_rm_vip_info.send_end_date
     *
     * @mbggenerated
     */
    public void setSendEndDate(Date sendEndDate) {
        this.sendEndDate = sendEndDate;
    }
}