package com.gd.datachx.entity;

import java.math.BigDecimal;
import java.util.Date;

public class TSysOperator {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_operator.oper_id
     *
     * @mbggenerated
     */
    private String operId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_operator.oper_name
     *
     * @mbggenerated
     */
    private String operName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_operator.oper_pw
     *
     * @mbggenerated
     */
    private String operPw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_operator.oper_status
     *
     * @mbggenerated
     */
    private String operStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_operator.oper_type
     *
     * @mbggenerated
     */
    private String operType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_operator.last_time
     *
     * @mbggenerated
     */
    private Date lastTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_operator.output_rate
     *
     * @mbggenerated
     */
    private BigDecimal outputRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_operator.branch_no
     *
     * @mbggenerated
     */
    private String branchNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_operator.data_grant
     *
     * @mbggenerated
     */
    private String dataGrant;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_operator.confirm_pw
     *
     * @mbggenerated
     */
    private String confirmPw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_operator.cash_grant
     *
     * @mbggenerated
     */
    private String cashGrant;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_operator.limit_discount
     *
     * @mbggenerated
     */
    private BigDecimal limitDiscount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_operator.save_discount
     *
     * @mbggenerated
     */
    private BigDecimal saveDiscount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_operator.contral_center
     *
     * @mbggenerated
     */
    private String contralCenter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_operator.price_grant
     *
     * @mbggenerated
     */
    private String priceGrant;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_operator.group_id
     *
     * @mbggenerated
     */
    private String groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_operator.oper_flag
     *
     * @mbggenerated
     */
    private String operFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_operator.charge
     *
     * @mbggenerated
     */
    private String charge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_operator.area_manager
     *
     * @mbggenerated
     */
    private String areaManager;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_operator.grant_type
     *
     * @mbggenerated
     */
    private String grantType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_operator.oper_id
     *
     * @return the value of t_sys_operator.oper_id
     *
     * @mbggenerated
     */
    public String getOperId() {
        return operId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_operator.oper_id
     *
     * @param operId the value for t_sys_operator.oper_id
     *
     * @mbggenerated
     */
    public void setOperId(String operId) {
        this.operId = operId == null ? null : operId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_operator.oper_name
     *
     * @return the value of t_sys_operator.oper_name
     *
     * @mbggenerated
     */
    public String getOperName() {
        return operName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_operator.oper_name
     *
     * @param operName the value for t_sys_operator.oper_name
     *
     * @mbggenerated
     */
    public void setOperName(String operName) {
        this.operName = operName == null ? null : operName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_operator.oper_pw
     *
     * @return the value of t_sys_operator.oper_pw
     *
     * @mbggenerated
     */
    public String getOperPw() {
        return operPw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_operator.oper_pw
     *
     * @param operPw the value for t_sys_operator.oper_pw
     *
     * @mbggenerated
     */
    public void setOperPw(String operPw) {
        this.operPw = operPw == null ? null : operPw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_operator.oper_status
     *
     * @return the value of t_sys_operator.oper_status
     *
     * @mbggenerated
     */
    public String getOperStatus() {
        return operStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_operator.oper_status
     *
     * @param operStatus the value for t_sys_operator.oper_status
     *
     * @mbggenerated
     */
    public void setOperStatus(String operStatus) {
        this.operStatus = operStatus == null ? null : operStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_operator.oper_type
     *
     * @return the value of t_sys_operator.oper_type
     *
     * @mbggenerated
     */
    public String getOperType() {
        return operType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_operator.oper_type
     *
     * @param operType the value for t_sys_operator.oper_type
     *
     * @mbggenerated
     */
    public void setOperType(String operType) {
        this.operType = operType == null ? null : operType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_operator.last_time
     *
     * @return the value of t_sys_operator.last_time
     *
     * @mbggenerated
     */
    public Date getLastTime() {
        return lastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_operator.last_time
     *
     * @param lastTime the value for t_sys_operator.last_time
     *
     * @mbggenerated
     */
    public void setLastTime(Date lastTime) {
        this.lastTime = lastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_operator.output_rate
     *
     * @return the value of t_sys_operator.output_rate
     *
     * @mbggenerated
     */
    public BigDecimal getOutputRate() {
        return outputRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_operator.output_rate
     *
     * @param outputRate the value for t_sys_operator.output_rate
     *
     * @mbggenerated
     */
    public void setOutputRate(BigDecimal outputRate) {
        this.outputRate = outputRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_operator.branch_no
     *
     * @return the value of t_sys_operator.branch_no
     *
     * @mbggenerated
     */
    public String getBranchNo() {
        return branchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_operator.branch_no
     *
     * @param branchNo the value for t_sys_operator.branch_no
     *
     * @mbggenerated
     */
    public void setBranchNo(String branchNo) {
        this.branchNo = branchNo == null ? null : branchNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_operator.data_grant
     *
     * @return the value of t_sys_operator.data_grant
     *
     * @mbggenerated
     */
    public String getDataGrant() {
        return dataGrant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_operator.data_grant
     *
     * @param dataGrant the value for t_sys_operator.data_grant
     *
     * @mbggenerated
     */
    public void setDataGrant(String dataGrant) {
        this.dataGrant = dataGrant == null ? null : dataGrant.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_operator.confirm_pw
     *
     * @return the value of t_sys_operator.confirm_pw
     *
     * @mbggenerated
     */
    public String getConfirmPw() {
        return confirmPw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_operator.confirm_pw
     *
     * @param confirmPw the value for t_sys_operator.confirm_pw
     *
     * @mbggenerated
     */
    public void setConfirmPw(String confirmPw) {
        this.confirmPw = confirmPw == null ? null : confirmPw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_operator.cash_grant
     *
     * @return the value of t_sys_operator.cash_grant
     *
     * @mbggenerated
     */
    public String getCashGrant() {
        return cashGrant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_operator.cash_grant
     *
     * @param cashGrant the value for t_sys_operator.cash_grant
     *
     * @mbggenerated
     */
    public void setCashGrant(String cashGrant) {
        this.cashGrant = cashGrant == null ? null : cashGrant.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_operator.limit_discount
     *
     * @return the value of t_sys_operator.limit_discount
     *
     * @mbggenerated
     */
    public BigDecimal getLimitDiscount() {
        return limitDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_operator.limit_discount
     *
     * @param limitDiscount the value for t_sys_operator.limit_discount
     *
     * @mbggenerated
     */
    public void setLimitDiscount(BigDecimal limitDiscount) {
        this.limitDiscount = limitDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_operator.save_discount
     *
     * @return the value of t_sys_operator.save_discount
     *
     * @mbggenerated
     */
    public BigDecimal getSaveDiscount() {
        return saveDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_operator.save_discount
     *
     * @param saveDiscount the value for t_sys_operator.save_discount
     *
     * @mbggenerated
     */
    public void setSaveDiscount(BigDecimal saveDiscount) {
        this.saveDiscount = saveDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_operator.contral_center
     *
     * @return the value of t_sys_operator.contral_center
     *
     * @mbggenerated
     */
    public String getContralCenter() {
        return contralCenter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_operator.contral_center
     *
     * @param contralCenter the value for t_sys_operator.contral_center
     *
     * @mbggenerated
     */
    public void setContralCenter(String contralCenter) {
        this.contralCenter = contralCenter == null ? null : contralCenter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_operator.price_grant
     *
     * @return the value of t_sys_operator.price_grant
     *
     * @mbggenerated
     */
    public String getPriceGrant() {
        return priceGrant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_operator.price_grant
     *
     * @param priceGrant the value for t_sys_operator.price_grant
     *
     * @mbggenerated
     */
    public void setPriceGrant(String priceGrant) {
        this.priceGrant = priceGrant == null ? null : priceGrant.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_operator.group_id
     *
     * @return the value of t_sys_operator.group_id
     *
     * @mbggenerated
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_operator.group_id
     *
     * @param groupId the value for t_sys_operator.group_id
     *
     * @mbggenerated
     */
    public void setGroupId(String groupId) {
        this.groupId = groupId == null ? null : groupId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_operator.oper_flag
     *
     * @return the value of t_sys_operator.oper_flag
     *
     * @mbggenerated
     */
    public String getOperFlag() {
        return operFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_operator.oper_flag
     *
     * @param operFlag the value for t_sys_operator.oper_flag
     *
     * @mbggenerated
     */
    public void setOperFlag(String operFlag) {
        this.operFlag = operFlag == null ? null : operFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_operator.charge
     *
     * @return the value of t_sys_operator.charge
     *
     * @mbggenerated
     */
    public String getCharge() {
        return charge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_operator.charge
     *
     * @param charge the value for t_sys_operator.charge
     *
     * @mbggenerated
     */
    public void setCharge(String charge) {
        this.charge = charge == null ? null : charge.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_operator.area_manager
     *
     * @return the value of t_sys_operator.area_manager
     *
     * @mbggenerated
     */
    public String getAreaManager() {
        return areaManager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_operator.area_manager
     *
     * @param areaManager the value for t_sys_operator.area_manager
     *
     * @mbggenerated
     */
    public void setAreaManager(String areaManager) {
        this.areaManager = areaManager == null ? null : areaManager.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_operator.grant_type
     *
     * @return the value of t_sys_operator.grant_type
     *
     * @mbggenerated
     */
    public String getGrantType() {
        return grantType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_operator.grant_type
     *
     * @param grantType the value for t_sys_operator.grant_type
     *
     * @mbggenerated
     */
    public void setGrantType(String grantType) {
        this.grantType = grantType == null ? null : grantType.trim();
    }
}