package com.gd.datachx.mapper;

import com.gd.datachx.entity.TBdItemBrand;

import java.util.List;

public interface TBdItemBrandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_item_brand
     *
     * @mbggenerated
     */
    int insert(TBdItemBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_item_brand
     *
     * @mbggenerated
     */
    int insertSelective(TBdItemBrand record);

    List<TBdItemBrand> selectBrandList();
}