package com.gd.datachx.mapper;

import com.gd.datachx.entity.TBdPaymentInfo;

import java.util.List;

public interface TBdPaymentInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_payment_info
     *
     * @mbggenerated
     */
    int insert(TBdPaymentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_payment_info
     *
     * @mbggenerated
     */
    int insertSelective(TBdPaymentInfo record);

    List<TBdPaymentInfo> selectPayments();
}