package com.gd.datachx.mapper;

import com.gd.datachx.entity.TBdSupcustInfo;

import java.util.List;

public interface TBdSupcustInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_supcust_info
     *
     * @mbggenerated
     */
    int insert(TBdSupcustInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_supcust_info
     *
     * @mbggenerated
     */
    int insertSelective(TBdSupcustInfo record);

    List<TBdSupcustInfo> selectSupcust();
}