package com.gd.datachx.mapper;

import com.gd.datachx.entity.TRmVipSavelist;

import java.util.Date;
import java.util.List;

public interface TRmVipSavelistMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rm_vip_savelist
     *
     * @mbggenerated
     */
    int insert(TRmVipSavelist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rm_vip_savelist
     *
     * @mbggenerated
     */
    int insertSelective(TRmVipSavelist record);

    List<TRmVipSavelist> selectVisaFlows(Date rechargeRecordDate);
}