package com.gd.datachx.mapper;

import com.gd.datachx.entity.TRmVipAcclist;

import java.util.Date;
import java.util.List;

public interface TRmVipAcclistMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rm_vip_acclist
     *
     * @mbggenerated
     */
    int insert(TRmVipAcclist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rm_vip_acclist
     *
     * @mbggenerated
     */
    int insertSelective(TRmVipAcclist record);

    List<TRmVipAcclist> selectCarPayList(Date carPayDate);
}