package com.gd.datachx.mapper;

import com.gd.datachx.entity.TSysOperator;

import java.util.List;

public interface TSysOperatorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_operator
     *
     * @mbggenerated
     */
    int insert(TSysOperator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_operator
     *
     * @mbggenerated
     */
    int insertSelective(TSysOperator record);

    List<TSysOperator> selectCashierList();
}